### ISSUE TITLE
cmake 2.8.11 hits configure error finding pthreads library due to pthreads test target

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1264]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on June 06, 2013 11:30:56_

http://stackoverflow.com/questions/16909008/cmake-error-try-compile-pthreads-of-type-executable -- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
CMake Error at /usr/share/cmake/Modules/CheckLibraryExists.cmake:41 (try_compile):
   Only libraries may be used as try_compile IMPORTED LINK_LIBRARIES.  Got
   pthreads of type EXECUTABLE.
Call Stack (most recent call first):
   /usr/share/cmake/Modules/FindThreads.cmake:58 (CHECK_LIBRARY_EXISTS)
   tests/app_suite/CMakeLists.txt:58 (find_package)
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE

This is from a change in cmake between 2.8.10.2 and 2.8.11: 236133e79e2d047810eeba90915e38d9861e2a22 I believe.

Re-naming the pthreads test target fixes the problem.

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1264_

**Comment by tanajikamble13** [comment]
i am not getting what u mean Re-naming the pthreads test target. Please elaborate more

**Comment by derekbruening** [comment]
svn r1412 is 9bbe834ae02a3858d1d9fd39890a1f67d325e769 and as you can see it changes the name of the cmake target from "pthreads" to "pthread_test".
