### ISSUE TITLE
Application exits with abnormal code 0xc000041d due to early thread created by app

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1355]
_From [laurence...@gmail.com](https://code.google.com/u/111262087262314931882/) on October 24, 2013 11:26:30_

What steps will reproduce the problem? 1.Run application (can't be provided) under Dr. Memory, with the option "-leaks_only"
2.After short while application crashes with error message ~~Dr.M~~ WARNING: application exited with abnormal code 0xc000041d. 3. What is the expected output? What do you see instead? Application should continue to run without exiting. When run with the "-debug -dr_debug" option, it displays the following message in a 'DynamioRIO Notice' pop-up just before crashing: 

'LdrLoadDll reached by unexpected unknown thread <threadID>'

See also attached image of dialog. What version of the product are you using? On what operating system? Dr. Memory version 1.6.0 -- build 2.
Windows 7 Professional SP1.

Does the problem go away when running in light mode (pass "-light" to Dr.
Memory)?  What about when running with the options "-leaks_only
-no_count_leaks -no_track_allocs"?
When running in light mode the application exits with same error code. Problem does goes away with "-leaks_only -no_count_leaks -no_track_allocs".

**Attachment:** [dynamorio_notice.png](http://code.google.com/p/drmemory/issues/detail?id=1355)

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1355_

**Comment by Engineerumair** [comment]
Was this issue resolved if yes then please tell me resolution of this issue

**Comment by derekbruening** [comment]
Early extra thread handling was added in https://github.com/DynamoRIO/dynamorio/commit/9c95ba5aadd1dcc42b1e43161ad0193ca561a071

**Comment by Engineerumair** [comment]
@derekbruening I got this exception due to keyboardmousehooking dll that call setwindowshookEx but don't call unhookwindowsEx it crashes because I use instance of KeyBoardMouseKooking and it provides only start and stop where its finalize method is protected and can't be called from its instance until I inherit

**Comment by Engineerumair** [comment]
How could I use extra thread handling in windows ?

**Comment by derekbruening** [comment]
This issue tracker is for the Dr. Memory memory debugging tool.  It sounds like you're hitting a 0xC000041D exception in a native application that is not running under Dr. Memory nor its tool platform DynamoRIO?  Our tools are using dynamic binary translation and the bugs encountered likely do not mirror native bugs.  The problem here is that a thread was created that ran outside of the tool's control and it's the mix of managed and unmanaged execution that resulted in the exception.

**Comment by Engineerumair** [comment]
I have same problem with managed and unmanaged code where I used Drmemory to see details of exception i know reasons but don't know how to solve. please help how to solve it

**Comment by derekbruening** [comment]
Please clarify: you have an application that runs correctly without a crash by itself, but when you run it under Dr. Memory it crashes with 0xC000041D?

**Comment by Engineerumair** [comment]
No application does not crash due to Drmemory it crashes due to Keyboardmousehooking dll so I want ask about solution how you resolve for dr-memory i would do try to do same

**Comment by derekbruening** [comment]
Our solution was to take over the extra thread to ensure everything is under the tool's control, thus avoiding races and strange interactions in cases where the tool assumes it has sole control.  As mentioned, I do not think there are any parallels here to solving this exception in a native application outside of a dynamic binary translation tool, unfortunately.
