### ISSUE TITLE
ASSERT (shadow.c:761: false "fail to check value in shadow mmeory") in tests/operators

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1462]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on March 04, 2014 13:51:24_

This happened once on Linux in my pre-commit test suite.  I have never seen it before, nor since (can't repro):

drmemory-dbg-32: 56 tests passed, **** 1 tests failed: ****
        operators => \~~Dr.M~~ ASSERT FAILURE (thread 4610): /work/drmemory/build_suite/src/drmemory/shadow.c:761: false (fail to check value in shadow mmeory)

                CMake Error at runtest.cmake:447 (message):;  \~~Dr.M~~ ASSERT FAILURE (thread 4610):
                  /work/drmemory/build_suite/src/drmemory/shadow.c:761: false (fail to check
                  value in shadow mmeory)

Happened at the end, it looks like:

\<Stopping application /work/drmemory/build_suite/build_drmemory-dbg-32/tests/operators (4610)>
\~~Dr.M~~ ASSERT FAILURE (thread 4610): /work/drmemory/build_suite/src/drmemory/shadow.c:761: false (fail to check value in shadow mmeory)

Hmm, typo in that msg ("mmeory")

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1462_

**Comment by zhaoqin** [comment]
I can reproduce it if I disable the ASLR.
```
> ./bin/drmemory -- ./tests/operators
...
<Stopping application /usr/local/google/home/zhaoqin/Workspace/DrMemory/builds/build_suite/build_drmemory-dbg-32/tests/operators (5968)>
~~Dr.M~~ ASSERT FAILURE (thread 5968): /usr/local/google/home/zhaoqin/Workspace/DrMemory/drmemory.git/drmemory/shadow.c:901: false (fail to check value in shadow mmeory)
```
