### ISSUE TITLE
cmake 2.8.12 policy CMP0022 warns about INTERFACE_LINK_LIBRARIES

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1481]
_From [priyankb...@gmail.com](https://code.google.com/u/113079830533410703845/) on March 21, 2014 18:35:33_

What steps will reproduce the problem? 1.cmake-gui .. on command line
2.configure
3.Visual Studio 10
4.Use Default Native Compiler
5.Finish What is the expected output? What do you see instead? Expected Output: Configuring done with no warning's
Result   Output: Getting lots of warnings and then Configuring Done. What version of the product are you using? On what operating system? Using cmake version 2.8.12.2 using Qt 4.6.2 , Windows 8.1 x64 build Please provide any additional information below. Warning's:
CMake Warning (dev) at CMakeLists.txt:1428 (export):
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "drsyscall" has an INTERFACE_LINK_LIBRARIES property which differs
  from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

```
dynamorio;drmgr;drcontainers;C:/drmemory-original/build/dynamorio/core/ntdll_imports.lib
```

  LINK_INTERFACE_LIBRARIES:

Call Stack (most recent call first):
  drsyscall/CMakeLists.txt:89 (export_target)
  drsyscall/CMakeLists.txt:108 (export_drsyscall_target)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in dynamorio/ext/drsyms/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "drsyms" has an INTERFACE_LINK_LIBRARIES property which differs from
  its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

```
libcpmt;libcmt;dynamorio;dbghelp;C:/drmemory-original/build/dynamorio/ext/drsyms/dbghelp_imports.lib;drcontainers;C:/drmemory-original/dynamorio/ext/drsyms/libelftc-pecoff/lib32/dwarf.lib;C:/drmemory-original/dynamorio/ext/drsyms/libelftc-pecoff/lib32/elftc.lib
```

  LINK_INTERFACE_LIBRARIES:

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:1428 (export):
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "drsymcache" has an INTERFACE_LINK_LIBRARIES property which differs
  from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

```
dynamorio;drcontainers;drmgr;drsyms
```

  LINK_INTERFACE_LIBRARIES:

Call Stack (most recent call first):
  drsymcache/CMakeLists.txt:61 (export_target)
  drsymcache/CMakeLists.txt:78 (export_drsymcache_target)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:1428 (export):
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "umbra" has an INTERFACE_LINK_LIBRARIES property which differs from
  its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

```
dynamorio;drmgr;drcontainers;C:/drmemory-original/build/dynamorio/core/ntdll_imports.lib
```

  LINK_INTERFACE_LIBRARIES:

Call Stack (most recent call first):
  umbra/CMakeLists.txt:64 (export_target)
  umbra/CMakeLists.txt:84 (export_umbra_target)
This warning is for project developers.  Use -Wno-dev to suppress it.

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1481_

**Comment by hgreving2304** [comment]
This may require changing all external projects to CMP0022 NEW as well, because the exported target doesn't seem to set LINK_INTERFACE_LIBRARIES property even when setting the EXPORT_LINK_INTERFACE_LIBRARIES flag. I am checking with the cmake mailing list.
