### ISSUE TITLE
Switch from NSIS to a WiX-based installer

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1620]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on September 08, 2014 15:00:58_

Split from issue #1608 Quoting from there:

3) Switch from NSIS to WiX.  CPack 2.8.11+ supports WiX.  WiX is MSI-based and so would have built-in uninstall support and also support for automatically replacing an existing installation.  It should support everything we're currently doing with NSIS, and may make some things easier like writing the reg keys for the VS External Tool support.

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1620_

**Comment by blueelvis** [comment]
I think that adding the option to Explorer Integration would be suited very well on Windows. Imagine, no matter where the application's executable is located, just right click, Send To --> "Dr Memory" shortcut.

More Info - http://blogs.msdn.com/b/amb/archive/2012/02/19/how-to-add-notepad-shortcut-in-quot-send-to-quot-menu-on-windows-7.aspx

**Comment by derekbruening** [comment]
blueelvis, thank you for the suggestion.  Could you open a new, separate issue to track it?  Let's keep this issue just on getting the features from our existing NSIS installer implemented in WiX.

**Comment by blueelvis** [comment]
@derekbruening - Issue created over here - https://github.com/DynamoRIO/drmemory/issues/1683

**Comment by derekbruening** [comment]
Just for the record:

There's something wrong with the "NOT Installed AND NOT REMOVE" trigger for add_vs_tool.  If you make it Return="check" you can see that it tries to run it on uninstall!  You end up with this error: 

"There is a problem with this Windows Installer package. A program required for this install to complete could not be run."

Event log says: Product: Dr. Memory -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: add_vs_tool, location: C:\Program Files (x86)\Dr. Memory\bin\vs_external_tool.exe, command: "C:\Program Files (x86)\Dr. Memory\bin\drmemory.exe"
