### ISSUE TITLE
Not supported on Yosemite.

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1643]
_From [nico...@gmail.com](https://code.google.com/u/109078064477140030271/) on September 28, 2014 17:53:47_

\<Application /Users/nicomda/NetBeansProjects/DrMemory-MacOS-1.8.0-8/bin/drmemory (1107) is running on an unsupported operating system (14.0.0)>

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1643_

**Comment by bennyty** [comment]
Can anyone confirm that Dr. Memory works now on Yosemite? I've been waiting to update specifically for Dr. Memory.

**Comment by derekbruening** [comment]
Yes, support was added in 167555f7d3f544184295b35a67f98043c55b5d9f.

**Comment by derekbruening** [comment]
The 1.8.1 release and later support Yosemite (xref https://github.com/DynamoRIO/drmemory/releases). Somehow this issue was not closed back when the support was added.
