### ISSUE TITLE
Executables created by Delphi crash

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1646]
_From [tim.lebe...@gmail.com](https://code.google.com/u/104287123505128759867/) on October 06, 2014 08:09:41_

What steps will reproduce the problem? 1. Create an empty console based application in Delphi XE5
2. Run it under Dr. Memory What is the expected output? What do you see instead? The application completes successfully, but the application crashes. What version of the product are you using? On what operating system? 1.7.0.5, Windows 7 64 bit (Microsoft Windows [Version 6.1.7601])

Does the problem go away when running in light mode (pass "-light" to Dr.
Memory)?  What about when running with the options "-leaks_only
-no_count_leaks -no_track_allocs"?
the application crashes in both cases with the same error Does the problem go away when using the most recent build from http://build.chromium.org/p/client.drmemory/builds/? no Try the debug version of Dr. Memory and of its underlying engine DynamoRIO by passing "-debug -dr_debug -pause_at_assert" to drmemory.exe. Are any messages reported? Here are the messages:

=====================================================
_assert TestDrMemory.exe                                                                                                    
WARNING: unable to locate results file since can't open C:\Users\lebedkov\Downloads\drmemory\logs/resfile.2996: 2           
There was likely an early crash, perhaps due to interference from invasive security software.  Try disabling other software.
\~~Dr.M~~ WARNING: application exited with abnormal code 0xc0000005                                                          
===================================================== Please provide any additional information below.  Please also see the "Narrowing Down the Source of the Problem" section of https://code.google.com/p/drmemory/wiki/Debugging . Please let me know how to send you the executable. The issue tracker says "Issue attachment storage quota exceeded."

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=1646_

**Comment by derekbruening** [comment]
I tried running TestDrMemory/src/Win32/Debug/TestDrMemory.exe from the zip file under Dr. Memory 1.8.0-8 (as well as 1.7.0-5) and it seems to run just fine: exit code 0, normal exit, no signs of something being wrong.  I tried both with DEP on and off (opt-out vs opt-in).  No exception is seen.

Given that I cannot reproduce, could you provide log files from debug runs where this app crash happens?  Could you run with the following options:

```
-debug -dr_debug -dr_ops "-loglevel 2" -verbose 2
```

And provide the drmemory/logs/ directory after the run?  Or if you want to zero in on the particular subdirs, they will look like this with the pid from your run substituted:

```
~/DrMemory-Windows-1.8.0-8/drmemory/logs/dynamorio/TestDrMemory.exe.1524.00000000/
~/DrMemory-Windows-1.8.0-8/drmemory/logs/DrMemory-TestDrMemory.exe.1524.000/
```

**Comment by tim-lebedkov** [comment]
It works now. The problem was ConEmu. If I use the default Windows console, Dr. Memory 1.7.0 build 5 works.

**Comment by derekbruening** [comment]
Xref #1517

**Comment by derekbruening** [comment]
The latest nightly build http://build.chromium.org/p/client.drmemory/builds/DrMemory-Windows-1.8.16469-0x065c007-sfx.exe should work when run within a hook-enabled ConEmu

**Comment by derekbruening** [comment]
xref DynamoRIO/dynamorio#1597
