### ISSUE TITLE
suppress problem in windows

### ISSUE THREAD

**Issue by SomeOne667** [DynamoRIO/drmemory#1664]
Tool reports the error:
"
Dr. Memory version 1.8.0
         Running <snip>
         Malformed suppression:
system call NtUserMessageCall
The last frame is incorrect!

Frames should be one of the following:
 module!function
 module!...
 <module+0xhexoffset>
 <not in a module>
 system call Name
 *
 ...
         Usage error: Malformed suppression. See the log file for the details.  Aborting.
         WARNING: application exited with abnormal code 0xffffffff
"
seems wrong

**Comment by derekbruening** [comment]
Without information on how to reproduce we'll have to close this.
