### ISSUE TITLE
git_review.sh: "Final commit log:" is empty in rietveld

### ISSUE THREAD

**Issue by groleo** [DynamoRIO/drmemory#1671]
introduced by me, in 1e1f894
fixed by:
```
-        msg=$(printf "Committed as ${hashurl}${hash}\n\nFinal commit log:" \
+        msg=$(printf "Committed as ${hashurl}${hash}\n\nFinal commit log:%s" \
```

**Comment by derekbruening** [comment]
There's no need to open a new issue for a bug in a just-committed CL that will be fixed immediately, esp. when the commit had its own issue -- simply re-open that issue.  Also, this is in the wrong tracker (drmemory instead of dynamorio).

**Comment by groleo** [comment]
Got it.
