### ISSUE TITLE
Comodo Internet Security 8.1 makes Dr. Memory unable to find find system calls

### ISSUE THREAD

**Issue by tpgit** [DynamoRIO/drmemory#1686]
DrMemory-Windows-1.8.0-8.exe
Windows 7 SP1 64bit 
Visual Studio 2008 SP1
Comodo Internet Security 8.1

See "Detecting file handle leaks on Windows 7?" [1] for any needed background details.

Having the Comodo Internet Security 8.1 anti-virus Security Suite [2] installed, even if all its features are disabled, causes Dr. Memory to report 130 or so "WARNING: could not find system call" messages in global.*.log when I run:

    drmemory -debug -verbose 3 -handle_leaks_only -- handleleak.exe

I get the following assert:

    ~Dr.M~ ASSERT FAILURE (thread 8032): d:\drmemory_package\common\utils.c:884: ok_to_fail (error finding required syscall #)
    ~Dr.M~ WARNING: application exited with abnormal code 0xffffffff

Investigating with WinDbg, I can see that ntdll!NtClose for example, disassembles to:

    ntdll!NtClose:
    77a7f9e0 ff251e00ae71    jmp     dword ptr ds:[71AE001Eh]
    77a7f9e6 c9              leave
    77a7f9e7 8d542404        lea     edx,[esp+4]
    77a7f9eb 64ff15c0000000  call    dword ptr fs:[0C0h]
    77a7f9f2 83c404          add     esp,4
    77a7f9f5 c20400          ret     4

If I open Memory window, and enter 71AE001Eh with display format = Pointer and Sy? I see:

    71ae001e 71af000a 

If I then disassemble 71af000a I see:

    No prior disassembly possible
    71af000a 57              push    edi
    71af000b 52              push    edx
    71af000c 51              push    ecx
    71af000d 50              push    eax
    71af000e bf3b00af71      mov     edi,71AF003Bh
    71af0013 8b542410        mov     edx,dword ptr [esp+10h]
    71af0017 b918010000      mov     ecx,118h
    71af001c 33c0            xor     eax,eax
    71af001e f00fb15701      lock cmpxchg dword ptr [edi+1],edx
    71af0023 7409            je      71af002e
    71af0025 83c70e          add     edi,0Eh
    71af0028 33c0            xor     eax,eax
    71af002a e2f2            loop    71af001e
    71af002c eb04            jmp     71af0032
    71af002e 897c2410        mov     dword ptr [esp+10h],edi
    71af0032 58              pop     eax
    71af0033 59              pop     ecx
    71af0034 5a              pop     edx
    71af0035 5f              pop     edi
    71af0036 e9a55c1101      jmp     guard32!Exported+0x128b0 (72c05ce0)

and doing lm m guard32:

    0:000> lm m guard32
    start    end        module name
    72bf0000 72c52000   guard32    (export symbols)       C:\Windows\SysWOW64\guard32.dll

Looking at the properties for  C:\Windows\SysWOW64\guard32.dll, it is owned by COMODO Internet Security.

OTOH, for the following configuration:

    Windows 7 SP1 64bit
    WinDbg 6.11.0001.404 X86
    DrMemory-Windows-1.8.0-8.exe
    Microsoft Windows SDK for Windows 7 and .NET Framework 3.5 SP1
    Comodo Internet Security 8.1 NOT installed

WinDbg shows this for ntdll!NtClose (as expected):

    ntdll!NtClose:
    76edf9e0 b80c000000      mov     eax,0Ch
    76edf9e5 33c9            xor     ecx,ecx
    76edf9e7 8d542404        lea     edx,[esp+4]
    76edf9eb 64ff15c0000000  call    dword ptr fs:[0C0h]
    76edf9f2 83c404          add     esp,4
    76edf9f5 c20400          ret     4

BTW, this issue might be related to "utils.c:884 error" #1661

On Mon, Feb 16, 2015 at 5:47 PM, 'Qin Zhao' via Dr. Memory Users <drmemory-users@googlegroups.com> wrote:
> On Mon, Feb 16, 2015 at 7:58 PM, TP <wingusr@gmail.com> wrote:
>> How likely do you think it will be for you to "fix" Dr Memory so it
>> can still find system calls even with Comodo Internet Security
>> installed?
>
> The system call finding is mostly pattern match, so if we know how Comodo
> hook those system calls, it is not impossible to do.
> I do not have Comodo, and supporting it is not our top priority right now, I
> am afraid we may not work on it anytime soon.
> Plus, I do not have Comodo.
>>
>> How hard would it be for me to do that? I imagine I'd have to fully
>> understand DynamicRio.
>
> If just to find system call, it may not very hard, as it is just simple
> pattern match.
> The code for finding syscall is at drsyscall/drsyscall_windows.c:
> syscall_num_from_name and syscall_num_from_wrapper
> and drmgr_decode_sysnum_from_wrapper in "dynamorio/ext/drmgr/drmgr.c"
>
> But Comodo may have many other strange things, which may or may not easy to
> handle.

On Tue, Feb 17, 2015 at 7:39 AM, 'Derek Bruening' via Dr. Memory Users <drmemory-users@googlegroups.com> wrote:
> On Mon, Feb 16, 2015 at 7:58 PM, TP <wingusr@gmail.com> wrote:
>>
>> How likely do you think it will be for you to "fix" Dr Memory so it
>> can still find system calls even with Comodo Internet Security
>> installed?
>>
>> How hard would it be for me to do that? I imagine I'd have to fully
>> understand DynamicRio.
>
> Please file an issue in our issue tracker.  This can be a complex topic with
> multiple possible solutions of varying difficulty and effectiveness.

[1] https://groups.google.com/forum/#!topic/DrMemory-Users/00-Gl2HOF9o

[2] https://www.comodo.com/home/internet-security/free-internet-security.php

**Comment by derekbruening** [comment]
Possible solutions to this particular Dr. Memory problem (note that hooks on system calls can also affect DR, and that other invasive security software behavior such as creating threads is also problematic: xref #1685, #1646, etc.):

1) Ideally we would love to take over from the very first user-mode instruction, which would be before any hooks are installed.  However, that is not easy on Windows where to read symbols we must use the 3rd-party dbghelp.dll, which is difficult to get running so early before any system libraries are initialized, even with our private loader.

2) Use a database of syscall numbers for ntoskrnl syscalls, just like we do for win32k.sys syscalls, instead of reading the ntdll wrappers.  This would be more of a pain to update to new Windows versions but it's already a pain for win32k.sys.

3) Have various heuristics for following into a hook while looking for the syscall number.
