### ISSUE TITLE
ERROR: failed to create process for "C\\ ....."

### ISSUE THREAD

**Issue by sigjon64** [DynamoRIO/drmemory#1687]
This message was due to Icelandic letters in the path where the file was, which I was trying to test with Dr.Memory.  I changed the changed the icelandic letters and then everything worked fine.

**Comment by derekbruening** [comment]
We need to implement the missing pieces in https://github.com/DynamoRIO/dynamorio/issues/943 to solve this

**Comment by bailehang** [comment]
My project don`t have Icelandic letters,but still failed to create process(err =2).

**Comment by zhaoqin** [comment]
Does it have other international letters?

**Comment by bailehang** [comment]
oh,the program path is wrong.The Dr.memory is OK

**Comment by bailehang** [comment]
This is really an active open source projects.I'm learning usage.老乡~

**Comment by bailehang** [comment]
Is the Drmemory a closed test environment? and if I detect my server program, you can not link standalone client, can do only make  start construction to ends destructor? @zhaoqin

**Comment by zhaoqin** [comment]
On Aug 1, 2016 9:42 PM, "bailehang" <notifications@github.com> wrote:
>
> Is the Drmemory a closed test environment? and if I detect my server
program, you can not link standalone client, can do only make start
construction to ends destructor? @zhaoqin
>
Sorry, I am not sure what you mean.

**Comment by derekbruening** [comment]
Before the fix:

```
% bin/drmemory -- d:/derek/nonäscii/hello.exe
ERROR: failed to create process (err=3) for "d:\derek\nonäscii\hello.exe":
```

After the fix:

```
% bin/drmemory -- d:/derek/nonäscii/hello.exe
~~Dr.M~~ Dr. Memory version 1.10.17041
~~Dr.M~~ Running "d:/derek/nonäscii/hello.exe"
Hello world!
Goodbye world!
~~Dr.M~~
~~Dr.M~~ NO ERRORS FOUND:
~~Dr.M~~       0 unique,     0 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
```
