### ISSUE TITLE
ASSERT Windows 8.1 64-bit tests all fail in umbra_init()

### ISSUE THREAD

**Issue by toshipiazza** [DynamoRIO/drmemory#1693]
The test suite's free test for build_drmemory-rel-64, as well as many other tests in the same build crash during initialization of umbra. Invoked with ```bin64\drmemory.exe -dr_ops "-msgbox_mask 15" -- tests\free.exe```

More information on crash:
```
<Starting application C:\RCOS_build\drmemory_test_suite\build_drmemory-dbg-64\tests\free.exe (5640)>
<Initial options = -no_dynamic_options -logdir 'C:\RCOS_build\drmemory_test_suite\build_drmemory-dbg-64\logs\dynamorio' -client_lib 'C:\RCOS_build\drmemory_test_suite\build_drmemory-dbg-64\bin64\debug\drmemorylib.dll;0;-logdir `C:\RCOS_build\drmemory_test_suite\build_drmemory-dbg-64\logs` -symcache_dir `C:\RCOS_build\drmemory_test_suite\build_drmemory-dbg-64\logs\symcache` -lib_blacklist C:\Windows*.d?? -resfile 5640 ' -code_api -probe_api -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -max_bb_instrs 256 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0K -reset_every_nth_pending 0 -vm_size 262144K -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -pad_jmps_mark_no_trace >
~~Dr.M~~ WARNING: 64-bit non-pattern modes are experimental
~~Dr.M~~ Dr. Memory version 1.8.16500
~~Dr.M~~ Running "tests\free.exe"
~~Dr.M~~ ASSERT FAILURE (thread 7072): C:\RCOS_build\drmemory\drmemory\drmemory.c:1856: false (fail to init Umbra)~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```

**Comment by derekbruening** [comment]
Qin, could you try to repro on 64-bit Win8.1.  What we saw was some allocation outside of the app library range (it was near private libraries), and Umbra failed when it saw it, resulting in an assert in debug and crash in release.  It would be nice if Umbra were more robust to such things.

**Comment by zhaoqin** [comment]
ok, this is caused by Win8.1 has a different memory layout as Win7.
For windows, we hardcode the segment that the app memory should be in:
    /* app1: [0x00000000'00000000, 0x00000010'00000000) */
    { (app_pc)(0x0 *SEGMENT_SIZE), (app_pc)(0x1 *SEGMENT_SIZE), 0},
    /* app2: [0x000007F0'00000000, 0x00000800'00000000) */
    { (app_pc)(0x7F*SEGMENT_SIZE), (app_pc)(0x80*SEGMENT_SIZE), 0},

Instead, Win8.1 has memory region more like:
[0x7ff8'00000000, 0x8000'00000000) instead of  [0x000007F0'00000000, 0x00000800'00000000)

**Comment by StephenHillAtViaivi** [comment]
I am using DrMemory-Windows-2.1.0-1.msi, on Win10 64-bit, and am seeing:

> 
> C:\Users\SHill\SHill_view\tm_build_system\build\unittest64>"C:\Program Files (x86)\Dr. Memory\bin64\drmemory.exe" -batch -- seg_unittest.exe
> ~~Dr.M~~ Dr. Memory version 2.1.0
> ~~Dr.M~~ Running "seg_unittest.exe"
> ~~Dr.M~~ Using system call file C:\Program Files (x86)\Dr. Memory\bin64\syscalls_x64.txt
> <Application C:\Users\SHill\SHill_view\tm_build_system\build\unittest64\seg_unittest.exe (19208).  Dr. Memory internal crash at PC 0x00000000009a2ad6.  Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'.  Program aborted.
> 0xc0000005 0x00000000 0x00000000009a2ad6 0x00000000009a2ad6 0x0000000000000000 0x000000001018cb9d
> Base: 0x0000000071000000
> Registers: eax=0x00000000000000ff ebx=0x00000000005f2e34 ecx=0x0000000000000008 edx=0x00000000fffffcff
>         esi=0x0000000000000000 edi=0x000000002366e010 esp=0x000000002366dfa0 ebp=0x0000000000000000
>         r8 =0x000000001018cb9d r9 =0x0000000000000008 r10=0x0000000000000001 r11=0x000000002366e050
>         r12=0x0000000000996b50 r13=0x0000000000100000 r14=0x0000000000000001 r15=0x0000000000996ba0
>         eflags=0x0000000000010286
> 2.1.0-1-(Mar 17 2019 23:59:56) WinVer=105;Rel=1803;Build=17134;Edition=Professional
> -no_dynamic_options -disasm_mask 8 -logdir 'C:\Users\SHill\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin64\release\drmemorylib.dll;0;-logdir `C:\Users\SHill\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\SHill\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\Windows*
> C:\Program Files (x86)\Dr. Memory\bin64\release\drmemorylib.dll=0x0000000000980000
> C:\Program Files (x86)\Dr. Memory\bin64\release/dbghelp.dll=0x0000000000d30000
> C:\Windows/system32/ADVAPI32.dll=0x00007ffe11450000
> C:\Windows/system32/sechost.dll=0x00007ffe10860000
> C:\Windows/system32/RPCRT4.dll=0x00007ffe10a90000
> C:\Windows/system32/msvcrt.dll=0x0000000000c20000
> C:\Windows/system32/kernel32.dll=0x0000000000ec0000
> C:\Windows/system32/KERNELBASE.d>
> ~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
> 
> C:\Users\SHill\SHill_view\tm_build_system\build\unittest64>"C:\Program Files (x86)\Dr. Memory\bin64\drmemory.exe" -batch -debug -- seg_unittest.exe
> ~~Dr.M~~ Dr. Memory version 2.1.0
> ~~Dr.M~~ Running "seg_unittest.exe"
> ~~Dr.M~~ ASSERT FAILURE (thread 6612): D:\drmemory_package\drmemory\drmemory.c:1969: false (fail to init Umbra)
> ~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff

**Comment by derekbruening** [comment]
(It looks like you opened #2184 to cover this: good, it is almost certainly a slightly different issue from this closed one.)
