### ISSUE TITLE
CRASH test suite wrap_operators test fails on jump Windows 8.1

### ISSUE THREAD

**Issue by toshipiazza** [DynamoRIO/drmemory#1694]
Invoked with ```bin\drmemory.exe -no_replace_malloc  -- tests\operators.exe``` on the build_drmemory-dbg-32 build.  Message returned was: ```encode_cti error: target beyond 8-bit reach```. With -verbose 4 we see that a long jump is interpreted as a short jump.

The log file can be found [here](http://pastebin.com/PeXQtymX)

**Comment by derekbruening** [comment]
For the record: operators.exe was built with VS2013 and ninja

**Comment by derekbruening** [comment]
It's the alignment check in the shadow table lookup:

```
 +990  m4 @0x192c28e4  8d 14 b2             lea    (%edx,%esi,4) -> %edx
 +993  m4 @0x18d4c3f8  64 80 3d d2 0e 00 00 cmp    %fs:0x00000ed2[1byte] $0x00
                       00
 +1001 m4 @0x18d40394  0f 85 fa ff ff ff    jnz    @0x18d4a5c4[4byte]
 +1007 m4 @0x18d4dc34  64 80 3d d6 0e 00 00 cmp    %fs:0x00000ed6[1byte] $0x00
                       00
 +1015 m4 @0x192c15e4  0f 85 fa ff ff ff    jnz    @0x18d4a5c4[4byte]
 +1021 m4 @0x18d4e074  f6 c2 03             test   %dl $0x03
==>
 +1024 m4 @0x18d4cb1c  75 fe                jnz    @0x18d4a5c4[4byte]
  ...
 +1156 m4 @0x18d4a5c4                       <label>
  ...
 +1178 L3              21 04 b2             and    %eax (%edx,%esi,4)[4byte] -> (%edx,%esi,4)[4byte]
```

**Comment by derekbruening** [comment]
toshipiazza, please confirm that this fixes the problem: I don't have a setup to reproduce the exact operators.exe symptoms.

**Comment by toshipiazza** [comment]
Can confirm that wrap_operators runs without errors on Ctest. I don't know if this is relevant though but wrap_operatorsMDd seems to time out when run in Ctest.

**Comment by derekbruening** [comment]
> Can confirm that wrap_operators runs without errors on Ctest. I don't know if this is relevant though but wrap_operatorsMDd seems to time out when run in Ctest.

Please file a new issue and investigate.
