### ISSUE TITLE
updating to latest DR causes annotations test to fail

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1705]
I want to update to the latest DR for early injection on Linux, but doing so causes the annotations test to fail on all platforms: an uninit is reported where there should be none.

```
Error #1: UNINITIALIZED READ: reading register eax
# 0 main        (0x08048772 <annotations+0x772>)
    /work/drmemory/git/src/tests/annotations.c:34
Note: @0:00:00.906 in thread 6898
Note: instruction: test   %eax %eax
```

This is what used to happen:

```
Matched valgrind client request pattern at 0x01131077:
rol    $0x00000003 %edi -> %edi 
rol    $0x0000000d %edi -> %edi 
rol    $0x0000001d %edi -> %edi 
rol    $0x00000013 %edi -> %edi 
xchg   %ebx %ebx -> %ebx %ebx 
```

But now DR removes that code pattern and the test fails.

Dr. Memory's annotation matching needs to be updated to use the new DR infrastructure.

Once the base is in place, other issues cover extra uses within DrMem: #61, #573, #1636, #1384.

Xref older issues #283 and #572, both of which essentially overlap with the DR-side
https://github.com/DynamoRIO/dynamorio/issues/1613 and can perhaps be closed once this issue is addressed.

**Comment by byron-hawkins** [comment]
I'm not quite sure how to resolve the dependency on DR annotations--the user is always able to turn off the DR annotations via cmake, so in that case what should the DrMemory annotation test do? Should it be turned off too? But I don't think the DrMemory build can see the DR cmake options (I tried several variations but couldn't make it work). In the meantime, here is a version of `drmemory/drmemory/annotations.c` that works with the new DR annotations:

```
#include "dr_api.h"
#include "drmgr.h"
#include "drmemory.h"
#include "annotations.h"
#include "utils.h"
#include "shadow.h"
#include "options.h"

static ptr_uint_t
handle_make_mem_defined_if_addressable(dr_vg_client_request_t *request)
{
#ifdef TOOL_DR_MEMORY
    app_pc start = (app_pc)request->args[0];
    ptr_uint_t len = request->args[1];

    /* No-op if we're not tracking definedness. */
    if (!options.shadowing || !options.check_uninitialized)
        return 1;

    shadow_set_non_matching_range(start, len, SHADOW_DEFINED,
                                  SHADOW_UNADDRESSABLE);
#endif

    /* XXX: Not sure what the proper return code is for this request, and most
     * apps don't care.
     */
    return 1;
}

void
annotate_init(void)
{
    dr_annotation_register_valgrind(DR_VG_ID__MAKE_MEM_DEFINED_IF_ADDRESSABLE,
                                    handle_make_mem_defined_if_addressable);
}

void
annotate_exit(void)
{
}
```
Note that this passes pre-commit on Linux, but some tests failed on Windows. Pre-commit takes an hour on my VirtualBox, so I'm still waiting to see if those same tests are failing on `master` too.

**Comment by derekbruening** [comment]
I will disable ANNOTATIONS for now for Dr. Memory's DR and let's put in your switch to using DR's infrastructure (should also remove DrMem's own Valgrind pattern matching too) as a separate step.
