### ISSUE TITLE
Trying to run drstrace against a .net 4.0 application, get too-big mem value to read

### ISSUE THREAD

**Issue by phuongnd08** [DynamoRIO/drmemory#1725]
C:\Program Files (x86)\BS Super Changer>drstrace -- MyApp.exe
<drstrace log file is .\drstrace.MyApp.exe.04884.0000.log>
ASSERT FAILURE: d:\drmemory_package\drstrace\drstrace.c:195: addr_size <= sizeof(mem_value) (too-big mem value to read)
What should I do?

**Comment by zhaoqin** [comment]
Can you please provide more information about the issue, for example, what the content before the ASSERT, what's the value of addr_size, on what syscall this assert is triggered.
Or is there is a way we can reproduce the problem?
Some debugging tips can be found at https://github.com/DynamoRIO/dynamorio/wiki/Debugging

**Comment by phuongnd08** [comment]
Seem like no simple task. The executable is a private one so I can't share.

**Comment by derekbruening** [comment]
Can you find out what system call this is?  That may be sufficient to figure out the problem.

**Comment by derekbruening** [comment]
Does a non-debug build of drstrace run correctly?

**Comment by svnpenn** [comment]
@derekbruening @zhaoqin can this be reopened? I can repro it.

**Comment by zhaoqin** [comment]
Please post more information about this system call.

**Comment by svnpenn** [comment]
The program I am trying to debug is `vcupgrade.exe`, which is part of
Visual Studio. It can be found:

    C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\vcupgrade.exe

The file I am working with is at:

    http://mp4v2.googlecode.com/svn/trunk/vstudio9.0/mp4art/mp4art.vcproj

To run, I can use this command:

    vupgrade mp4art.vcproj


However with `drstrace` it creates the error:

    > drstrace -- vcupgrade mp4art.vcproj
    <drstrace log file is .\drstrace.vcupgrade.exe.01468.0000.log>
    Microsoft (R) Visual C++ Project Convert Utility - Version 12.00.21005
    Copyright (C) Microsoft Corporation. All rights reserved.
    ASSERT FAILURE: d:\drmemory_package\drstrace\drstrace.c:195:
                     addr_size <= sizeof (mem_value) (too-big mem value to read)

**Comment by karcaw** [comment]
I am seeing a similar issue on a program called cview:

<drstrace log file is .\drstrace.cview.exe.02852.0000.log>
ASSERT FAILURE: d:\drmemory_package\drstrace\drstrace.c:195: addr_size <= sizeof(mem_value) (too-big mem value to read)

last entrys in log: 

NtOpenFile
	arg 0: 0x0028ce7c (type=HANDLE*, size=0x4)
	arg 1: 0x100001 (type=unsigned int, size=0x4)
	arg 2: len=0x18, root=0x0, name=34/34 "\??\C:\CView\bin\", att=0x40, sd=0x00000000, sqos=0x00000000 (type=OBJECT_ATTRIBUTES*, size=0x4)
	arg 3: 0x0028ce48 (type=IO_STATUS_BLOCK*, size=0x4)
	arg 4: FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE (type=named constant, value=0x7, size=0x4)
	arg 5: FILE_DIRECTORY_FILE|FILE_SYNCHRONOUS_IO_NONALERT|FILE_OPEN_FOR_BACKUP_INTENT (type=named constant, value=0x4021, size=0x4)
    succeeded =>
	arg 0: 0x0028ce7c => 0x428 (type=HANDLE*, size=0x4)
	arg 3: status=0x0, info=0x1 (type=IO_STATUS_BLOCK*, size=0x4)
	retval: 0x0 (type=NTSTATUS, size=0x4)
NtQueryDirectoryFile.FileBothDirectoryInformation
	arg 0: 0x428 (type=HANDLE, size=0x4)
	arg 1: 0x0 (type=HANDLE, size=0x4)
	arg 2: <null> (type=<function>, size=0x4)
	arg 3: 0x00000000 (type=void, size=0x4)
	arg 4: 0x0028ce48 (type=IO_STATUS_BLOCK*, size=0x4)
	arg 5: 0x0028ce90 (type=<struct>*, size=0x4)
	arg 6: 0x268 (type=unsigned int, size=0x4)
	arg 7: 0x3 (type=named constant, size=0x4)
	arg 8: 0x1 (type=bool, size=0x1)
	arg 9: 18/18 "cview.exe" (type=UNICODE_STRING*, size=0x4)
	arg 10: 0x0 (type=bool, size=0x1)

**Comment by zhaoqin** [comment]
```
0:000> dt -r2 pt
Local var @ 0x1dcae128 Type _cls_syscall_t*
0x1dcb2b2c 
   +0x000 sysnum           : 
      +0x000 number           : 50
      +0x004 secondary        : 3
   +0x008 sysinfo          : 0x00da4834 
      +0x000 num              : 
         +0x000 number           : 50
         +0x004 secondary        : 3
      +0x008 name             : 0x00da2ce4  "NtQueryDirectoryFile.FileBothDirectoryInformation"
      +0x00c flags            : 1
      +0x010 return_type      : 8
      +0x014 arg_count        : 11
```
In print_structure:
```
0:000> dv
  compound_type = 0x1dcad6d0
            buf = 0x1dcae1c4
           type = 0x1dcad6d0
            arg = 0x1dcae12c
           addr = 0x0022e031
     type_union = 0 ''
              i = 12
0:000> dt -r1 compound_type
Local var @ 0x1dcad5ec Type _drsym_compound_type_t*
0x1dcad6d0 
   +0x000 type             : 
      +0x000 kind             : 5
      +0x004 size             : 0x60
      +0x008 id               : 0x28
   +0x00c name             : 0x1dcad6e8  "_FILE_BOTH_DIR_INFORMATION"
   +0x010 num_fields       : 14
   +0x014 field_types      : 0x1dcad708  -> 0x1dcad740 
      +0x000 kind             : 1
      +0x004 size             : 4
      +0x008 id               : 4
0:000> ?? *compound_type->field_types[12]
struct _drsym_type_t
   +0x000 kind             : 6
   +0x004 size             : 0x18
   +0x008 id               : 0x38
```
_FILE_BOTH_DIR_INFORMATION can be found at
https://msdn.microsoft.com/en-us/library/windows/hardware/ff540235(v=vs.85).aspx

**Comment by zhaoqin** [comment]
The compound_type->field_types[12] should be `WCHAR ShortName[12]`, so the size is 0x18, and the kind is 6 (DRSYM_TYPE_ARRAY). However, `print_structure` calls `safe_read_field` to read, and cause the assert.
