### ISSUE TITLE
Install location ends up in unwritable ProgFiles somehow

### ISSUE THREAD

**Issue by algr** [DynamoRIO/drmemory#1730]
Successfully installed 1.8.1 build 0 on Windows 7 Enterprise using the installer.  But it then fails at startup:
```
C:\home>"c:\program files (x86)\dr. memory\bin\drmemory" -- a.exe
ERROR: cannot create c:\program files (x86)\dr. memory\drmemory\logs\symcache

<press enter to dismiss>
```
The logs directory has been set to read-only.  This is my work laptop, which has a security policy applied to it... I can install new applications but their install directories are set read-only and I can't change that.  That seems reasonable and I would expect other machines to have a similar policy in place.  The binaries/assets install directory really isn't the best default place for logs etc., a better approach would be to generate a path using the LOCALAPPDATA environment variable.

**Comment by derekbruening** [comment]
The default log directory on Windows is based on the APPDATA and as a fallback the USERPROFILE env vars.  If neither is set, it tries to use TMPDIR, TEMP, or TMP env vars.  Only if none of those 5 env vars is set does it give up and try to use the install dir.  We have never seen that happen.  It will probably be much easier for you to figure out what's going on as we do not have a reproducing instance.  Please investigate and see why your machine failed all of those env var checks, or maybe something else in the code which you can see here:  https://github.com/DynamoRIO/dynamorio/blob/master/libutil/dr_frontend_common.c#L119

**Comment by algr** [comment]
I think the problem is that the env vars are only used if this returns true, and it's not:
```
static bool
drfront_is_system_install_dir(const char *dir)
{
#ifdef WINDOWS
    return (strstr(dir, "Program Files") != NULL);
#else
    return (strstr(dir, "/usr/") == dir);
#endif
}
```
Several problems there, e.g. the real install location could be referenced as "program files (x86)" (as in my case) or "progra~2", both of which would fail the check; or some other directory could randomly have "Program Files" in its name, which would pass the check; or you could be running it from a remote mounted read-only installation directory on a server.  The last could be an issue for Linux also.

The other issue with using the install directory even if writeable, would be that you get a lot of logs created there and it fills up your disk space.  Even if you spotted that that your install directory was full, it might not be obvious what to delete, as you don't know what's part of the install and what's just logs.

I think it would be more robust to assume that the install directory is read-only or shared, and put the logs somewhere else.

**Comment by derekbruening** [comment]
The drfront_access check for being writable should fail and the env vars should be checked regardless of the result of drfront_is_system_install_dir().

**Comment by algr** [comment]
drfront_access checks for being writeable in the sense it checks it doesn't have the RO attribute, but that doesn't mean the current user has permissions to write it, see
https://msdn.microsoft.com/en-us/library/1w06ktdy.aspx

I'm not sure how you'd pre-emptively check permissions, it's usually easier just to go ahead and try... if you really do want to create it there.

Definitely there is a case-sensitive check going on:
```
C:\home>"c:\Program Files (x86)\dr. memory\bin\drmemory" -- c:\windows\system32\whoami
~~Dr.M~~ Dr. Memory version 1.8.1
~~Dr.M~~ Running "c:\windows\system32\whoami"
```
versus
```
C:\home>"c:\program files (x86)\dr. memory\bin\drmemory" -- c:\windows\system32\whoami
ERROR: cannot create c:\program files (x86)\dr. memory\drmemory\logs\symcache
```

**Comment by derekbruening** [comment]
We do not want to always put logs into a user profile dir, as we want our local install (tarball on unix, zip file on Windows) to be self-contained, local, and easily removable or moved.

**Comment by zhaoqin** [comment]
I cannot reproduce the error on my Win 7 Enterprise (Version 6.1 Build 7601: Service Pack 1)
```
C:\>"C:\Program Files (x86)\Dr. Memory\bin\drmemory" -version
Dr. Memory version 1.8.1 -- build 0

C:\>"C:\Program Files (x86)\Dr. Memory\bin\drmemory" -- hello.exe
~~Dr.M~~ Dr. Memory version 1.8.1
~~Dr.M~~ Running "hello.exe"
Hello world!
~~Dr.M~~
~~Dr.M~~ NO ERRORS FOUND:
~~Dr.M~~       0 unique,     0 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: C:\Users\zhaoqin\AppData\Roaming\Dr. Memory\DrMemory-hello.exe.7192.000\results.txt
```

**Comment by derekbruening** [comment]
> I cannot reproduce the error on my Win 7 Enterprise (Version 6.1 Build 7601: Service Pack 1)

It doesn't look like you varied the case?

**Comment by zhaoqin** [comment]
In `drfront_appdata_logdir`
```
    if (drfront_is_system_install_dir(root) ||
        drfront_access(root, DRFRONT_WRITE, &writable) != DRFRONT_SUCCESS ||
        !writable)
0:000> dt root
Local var @ 0xeae3bc Type char*
0x00eaf9a8  "c:\program files (x86)\dr. memory\build_x86_drm_dbg.git"
```
`drfront_is_system_install_dir(root)` returns false.
However, `drfront_access` returns true.
```
    r = _waccess(wfname, msdn_mode);

0:000> dv
          fname = 0x00eaf9a8 "c:\program files (x86)\dr. memory\build_x86_drm_dbg.git"
           mode = DRFRONT_WRITE (2)
            ret = 0x00eae3b3 ""
              r = 0
   status_check = DRFRONT_SUCCESS (0)
         wfname = wchar_t [260] "c:\program files (x86)\dr. memory\build_x86_drm_dbg.git"
      msdn_mode = 2
```
That's why we use "c:\program files (x86)\dr. memory\build_x86_drm_dbg.git" for the log and symcache directory.

**Comment by derekbruening** [comment]
Note that just trying to write to Program Files has complexities: modifications to files "pretend" to succeed and are redirected to VirtualStore.  As shown, creating a directory looks like it fails and is not redirected, but the point is that there are strange behaviors specific to the Program Files dir.

**Comment by derekbruening** [comment]
dd9804a32463b81ae0c3432579e0b38451e4bea8 added better checks for writability
