### ISSUE TITLE
Create a Dr. Fuzz feature

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/drmemory#1734]
Create a new extension to facilitate fuzz testing any function in the target app. The extension will include:

* an API for controlling the fuzzer from a client, which facilitates:
  * choosing the function to fuzz (potentially dynamic)
  * generating input for the target function (trivial mutators provided)
  * controlling the iteration count
  * observing target function execution (e.g. control flow activity, memory operations)
* a trivial "fuzz driver" client that loads configuration from a text file and does nothing but direct the fuzzer accordingly
* internal implementation of the fuzzing operations
  * the initial repeat mechanism will use dr_wrap with dr_redirect_execution
  * optimizations may be implemented later, such as fuzzing via clean calls with continuations

Migrated from DR issue [#1706](https://github.com/DynamoRIO/dynamorio/issues/1706)

**Comment by derekbruening** [comment]
This initial issue is complete and all further work is in separate issues such as #1797, #1801, #1802, #1830, #1837, #1842.
