### ISSUE TITLE
Dr. Memory internal crash at PC 0x7380896a

### ISSUE THREAD

**Issue by DavidEGrayson** [DynamoRIO/drmemory#1735]
An assertion is failing in readwrite.c, but it seems to not be a major problem for me because I can just run Dr. Memory with the `-leaks_only` option to work around it.  Here are the details:

*What steps will reproduce the problem?*

Sorry, I don't have a set of steps that other people can follow.  But the gist of it would be:

1. Install Dr. Memory 1.8.1 on Windows 8.1 64-bit.
2. Install [MSYS2](http://msys2.github.io/) and its *mingw-w64-i686-cmake*, *make*, *mingw-w64-i686-gcc*, and *mingw-w64-i686-catch* packages.
3. Use cmake to build a C/C++ library I have been working on and its test suite (run_test.exe).
4. Run the command `drmemory.exe ./run_test.exe`  in MSYS2's Win32 shell (bash).

I tried to simplify the code in my test suite to narrow down the problem, but about half of the things I do to simplify the code cause the bug to go away, so it is very inefficient.  For example, I might try removing a large block of code but that makes the bug go away, so then I have to put the code back and try each individual part of that code, and half of those cannot be removed either.  So the process of making a minimal code example is very hard.  I did manage to replace the `main` function with a simple `return 0`, but the bug keeps happening, perhaps because of some static constructors.

This version of Dr. Memory used to work fine for me, but it stopped working after I made one particular commit that refactored the inheritance tree of some C++ classes in my library.

*What is the expected output? What do you see instead?*

I would expect Dr. Memory to also tell me if any memory leaks were detected.  Instead, I see Dr. Memory produce the following output in my shell:

```
~~Dr.M~~ Dr. Memory version 1.8.1
~~Dr.M~~ Running "./run_test.exe"
<Application C:\Users\David\Documents\libusbp\build32\run_test.exe (195532).  Dr. Memory internal crash at PC 0x7380896a.  Please report this at http://drmemory.org/issues.  Program aborted.
0xc0000005 0x00000000 0x7380896a 0x7380896a 0x00000000 0x00000005
Base: 0x64f10000
Registers: eax=0x00000000 ebx=0x17942b18 ecx=0x1790adc8 edx=0x00000000
        esi=0x17942b68 edi=0x17cc1146 esp=0x1776df4c ebp=0x17719180
        eflags=0x000
version 5.0.16470, custom build
-no_dynamic_options -disasm_mask 8 -logdir 'C:\Users\David\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\release\drmemorylib.dll;0;-logdir `C:\Users\David\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\David\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist C:\WINDOWS*.d?? -resfile 195532 ' -code_api -probe_api -stack_size 56K -di
0x17719180 0x0040938c
0x6fecca18 0x6fecdadc
0x6fecf128 0x6fe59230
0x6fe59250 0xa5e96fec
C:\Program Files (x86)\Dr. Memory\bin\release\drmemorylib.dll=0x73800000
C:\Program Files (x86)\Dr. Memory\bin\release/dbghelp.dll=0x62790000
C:\WINDOWS/system32/msvcrt.dll=0x00640000
C:\WINDOWS/system32/kernel32.dll=0x02030000
C:\WINDOWS/system32/KERNELBASE.dll=0x021e0000>
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```

It also displays that information in a pop-up box.

*What version of the product are you using? On what operating system?*

I am using Dr. Memory 1.8.1 on Windows 8.1 64-bit.  I found the installation file in my Downloads folder from when I downloaded, and I verified that the SHA1 sum is c441acd2e3005a10ef3691b7b0ec3cdc135ce239, which matches what is displayed on the [bintray page](https://bintray.com/bruening/DrMemory/DrMemory-Windows-installer/view).

*Does the problem go away when running in light mode (pass "-light" to Dr.
Memory)?  What about when running with the options "-leaks_only
-no_count_leaks -no_track_allocs"?*

If I run `drmemory.exe -light ./run_test.exe` then the error still happens.  (At least some error happens at that PC location; I didn't check all the details.)

If I run `drmemory -leaks_only -no_count_leaks -no_track_allocs ./run_test.exe` then the error does not happen.

If I run `drmemory -leaks_only` then the error does not happen.  (I suppose that would be a good workaround for now.)

*Try the debug version of Dr. Memory and of its underlying engine DynamoRIO
by passing "-debug -dr_debug -pause_at_assert" to drmemory.exe. Are any
messages reported?*

Apparently an assertion is failing!  Here is what I get when I run it in debug mode:

```
$ drmemory.exe -debug -dr_debug -pause_at_assert ./run_test.exe
<Starting application C:\Users\David\Documents\libusbp\build32\run_test.exe (196472)>
<Initial options = -no_dynamic_options -logdir 'C:\Users\David\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;`-pause_at_assert` -logdir `C:\Users\David\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\David\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist C:\WINDOWS*.d?? -resfile 196472 ' -code_api -probe_api -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -max_bb_instrs 256 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0K -reset_every_nth_pending 0 -vm_size 262144K -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr -pad_jmps_mark_no_trace >
~~Dr.M~~ Dr. Memory version 1.8.1
~~Dr.M~~ Running "./run_test.exe"
<writing to executable region.>
<self-modifying code.>
<dr_fragment_app_pc is a DR/client pc>
~~Dr.M~~ ASSERT FAILURE (thread 196476): d:\drmemory_package\drmemory\readwrite.c:5805: save != NULL (missing bb info)
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```

**Comment by derekbruening** [comment]
Thank you for the detailed report.  If you are unable to supply a program that we can use to reproduce, and if the execution that resulted in the assert is relatively short, could you add logging and point us at the log files?  They will contain paths to your app and all the code run by your app but shouldn't have other PII.  I believe level 3 for both Dr. Memory and DR should be enough to figure out the assert (which hopefully is direct related to the crash).  Please run:

```
drmemory.exe -debug -dr_debug -verbose 3 -dr_ops "-loglevel 3" -pause_at_assert ./run_test.exe
```

**Comment by DavidEGrayson** [comment]
I was able to reproduce the problem again tonight.  Here are the logs:

http://www.davidegrayson.com/hold/drmemory_150709/

 The big log file ends with an assertion failure on line 5805 of readwrite.c.

Even though my main function returns right away, the big log is still 6 MB long.  So I am just trusting you that it doesn't contain any private info.  I'm OK with the name of the library leaking, and I'd be OK with emailing the binaries I was testing to you if it helps.

**Comment by derekbruening** [comment]
Thanks.  Could you provide the DR log files too?  They should be in a directory with the exe name and PID in its name inside the dynamorio/ subdir of the logs dir.

**Comment by DavidEGrayson** [comment]
OK, I found two HTML files in that area and added them to the directory.

**Comment by derekbruening** [comment]
BTW, these log files all compress very nicely, so sthg like a zip file or tgz would shrink them considerably

**Comment by derekbruening** [comment]
DrMem log:

```
new basic block @0x0041ee66 == run_test.exe!mark_section_writable+0xe6
in event_basic_block(tag=0x23e9114d) translating
TAG  0x23e9114d
 +0    L3              89 3e                mov    %edi -> (%esi)[4byte] 
 +2    L3              eb a1                jmp    $0x23e910f2 
END 0x23e9114d
ASSERT FAILURE (thread 145028): d:\drmemory_package\drmemory\readwrite.c:5805: save != NULL (missing bb info)
```

DR log:

```
Entry into F431(0x0041f13e).0x23e9100b 
        [run_test.exe]
ASYNCH intercepted exception in thread 145028 at pc 0x23e910fc
        exception code = 0xc0000005, ExceptionFlags=0x00000000
        record=0x00000000, params=2
        PC 0x23e910fc tried to write address 0x0040938c
check_for_modified_code: exception was write to 0x0040938c
check_for_modified_code: seg fault in exec-writable region @0x0040938c
found_modified_code: translating 0x23e910fc
recreate_app_pc -- translating from pc=0x23e910fc
building bb instrlist now *********************
interp: start_pc = 0x23e9114d
```

Very strange: so the app writes to its own code, yet when we go to translate it we decode from a code cache address instead of an app address?  Makes no sense.  There is no bb with a tag in the cache earlier on so there was no self-interp problem: just a problem getting the right tag here.

Would it be possible to obtain this application so we can reproduce it ourselves?

**Comment by DavidEGrayson** [comment]
Yeah, one way or another we can make that happen.  I'll try again to simplify the application this weekend so I can give you a minimal example.  If I fail, I can just send you a bundle with the EXE and the DLLs it depends on.

It'll be interesting to find out what this mingw-w64 compiler is doing being the scenes and why :-)

**Comment by DavidEGrayson** [comment]
As an aside: I'm going to be running `drmemory -debug ./run_test.exe` hundreds of times (from bash) as I try to narrow this bug down, and it's annoying to have to close a notepad window every time.  I figured out that I can put a dummy "notepad.exe" in my current working directory to prevent Dr. Memory from launching the real notepad, but I could not find any command-line option to suppress running notepad.

**Comment by derekbruening** [comment]
> but I could not find any command-line option to suppress running notepad.

-batch

**Comment by DavidEGrayson** [comment]
I was able to get a sense of what code simplifications made the bug go away and which did not, and was therefore able to simplify the code a lot.  It is still over 1000 lines though, and that doesn't count the Catch framework (catch.hpp).  This should have all the files you need to reproduce the bug:

http://www.davidegrayson.com/hold/drmemory_150709/bug_repro_150711.zip

I included an EXE and the DLLs so you can just run that.  If you want to recompile it yourself using cmake/gcc/MSYS2 then all the files necessary for that are also there:

~~~~
mkdir build
cd build
cmake -G"MSYS Makefiles" ..
make
drmemory ./run_test.exe
~~~~

If it matters, I was using the latest version of catch (1.2.1); the MSYS2 package has not been update at the moment.

**Comment by derekbruening** [comment]
I can reproduce.  The code modifications are from MinGW relocating itself:

```
_pei386_runtime_relocator+0x27e
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/pseudo-reloc.c:292+0x0
```

It runs fine under plain DR, but crashes with the bad translation and what looks like a selfmod page that should be writable but is not under any form or DrMem.  Have not nailed down the precise bug yet.

**Comment by derekbruening** [comment]
The problem is that the stored copy of the app code for selfmod xl8 recreation (in case the app's copy has changed) is passed to the bb builder for decoding, and that pc is used as the tag for the client, who rightly complains.  We just need to pass the "pretend pc" original app pc.

**Comment by DavidEGrayson** [comment]
Cool, I'm glad you're figuring this out.  The pseudo-reloc.c file you mentioned can be found in`git://git.code.sf.net/p/mingw-w64/mingw-w64`.  Line 292 is a call to `memcpy`.

I am interested in knowing what's going on.  If you're trying to explain the bug to me, I don't fully know what these phrases mean:

* bad translation
* not under any form or DrMem
* selfmod xl8 recreation
* bb builder

**Comment by derekbruening** [comment]
> I am interested in knowing what's going on.  If you're trying to explain the bug to me, I don't fully know what these phrases mean:

Sorry, I was mostly explaining it to myself.

> * bad translation

Attempting to translate a machine context from the kernel in our code cache back to an application context, but using the what I thought was the wrong address.

> * not under any form or DrMem

Typo: s/or/of/

> * selfmod xl8 recreation

Translation (see above) of code that modifies other code on the same page or region (which we call "selfmod" even if it's not really modifying itself and is just modifying nearby code) via recreation == re-building the corresponding dynamic basic block and re-applying all tool transformations (as opposed to storing translation info).

> * bb builder

Basic block builder

> Do you know why the bug is so fragile?  There were so many things I could do that would make Dr. Memory start working, such as removing a call to a DLL function.

The bug depends on the MinGW relocation code triggering the selfmod fault.  Maybe your changes affected the MinGW behavior.  DR's selfmod handling also has dynamic components depending on counts of writes.

I have the bug fixed locally and will commit it soon after more testing.  First I wanted to resolve the leak scan which seems to be very slow for this MinGW app: #1770.

**Comment by DavidEGrayson** [comment]
Thanks!
