### ISSUE TITLE
Crash running from Visual Studio 2013

### ISSUE THREAD

**Issue by steve-andrews** [DynamoRIO/drmemory#1746]
![drmemoryinternalerror](https://cloud.githubusercontent.com/assets/13557204/9011993/184e73e0-3777-11e5-8c1f-78043ad2f741.png)

**Comment by steve-andrews** [comment]
Crash also happens running standalone, outside Visual Studio.

Running the debug build:
~~14712~~ ASSERT FAILURE (thread 14712): d:\drmemory_package\drmemory\drmemory.c:1152: mc.xsp <= (reg_t)teb->StackBase && mc.xsp > (reg_t)teb->StackLimit (initial xsp for thread invalid)~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff

**Comment by steve-andrews** [comment]
There is no crash running with the -light option.
There is no crash running with the -handle_leaks_only option.

**Comment by steve-andrews** [comment]
The issue has been resolved in:

Dr. Memory version 1.8.16647 build 62713762 built on Jul 31 2015 14:34:48.

**Comment by derekbruening** [comment]
Good to hear.  Thanks for trying the latest build.
