### ISSUE TITLE
DRload input file not closed

### ISSUE THREAD

**Issue by maddin200** [DynamoRIO/drmemory#1804]
in file dynamorio\tools\DRload.c line 258 missing fclose(f);

**Comment by derekbruening** [comment]
This belongs in the DynamoRIO tracker as it is unrelated to Dr. Memory (the tool DRload is not used by or shipped with Dr. Memory).  The handle will be closed by the kernel on process exit, so there is no leak, but it is good practice to close it.

**Comment by derekbruening** [comment]
Moved to https://github.com/DynamoRIO/dynamorio/issues/1819
