### ISSUE TITLE
false positive on GetClipboardFormatNameW

### ISSUE THREAD

**Issue by mistmist** [DynamoRIO/drmemory#1824]
DrMemory 1.9.0-4 reports a UNINITIALIZED READ on this call, despite the 2 in-parameters being constants:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms649040%28v=vs.120%29.aspx

    cl.exe -Zi foo2.cc user32.lib

    #include <windows.h>
    #include <stdio.h>
    
    int main()
    {
        WCHAR buf[257]; // "Null terminator isn't counted" says DataFmtTransl.cxx
        int ret = GetClipboardFormatNameW(49283, buf, 256);
    //    fprintf(stderr, "***%d***\n", ret);
    //    for (int i = 0; i <= ret; ++i)
    //        fprintf(stderr, "***%d***", buf[i]);
        return ret;
    }

Running it with "drmemory.exe foo.exe" on Windows 7:

    Dr. Memory version 1.9.0 build 4 built on Oct  2 2015 13:13:14
    Dr. Memory results for pid 3832: "foo2.exe"
    Application cmdline: "foo2.exe"
    Recorded 116 suppression(s) from default C:\Users\ms\DrMemory-Windows-1.9.0-4\bin\suppress-default.txt
    
    Error #1: UNINITIALIZED READ: reading 0x003ffca2-0x003ffca4 2 byte(s) within 0x003ffca2-0x003ffca4
    # 0 system call NtUserGetClipboardFormatName UNICODE_STRING.MaximumLength
    # 1 main                                                                       [c:\cygwin\tmp\foo2.cc:8]
    Note: @0:00:00.359 in thread 3976

Running it with "-light" reports no error.
"-debug -dr_debug -pause_at_assert" does not print anything interesting.

**Comment by mistmist** [comment]
Okay, the next false positive i see is caused by GetClipboardFormatNameW as well, it is the out-parameter buffer - reading it yields UNINITIALIZED READ multiple times.

This can be seen in the above reproducer too, when uncommenting the printfs, 18 characters are printed and 2 different UNINITIALIZED READ stacks reported 17 times each.

**Comment by derekbruening** [comment]
Thanks for filing these.  The system call table is what controls these.  Do you see an error in the entry at https://github.com/DynamoRIO/drmemory/blob/master/drsyscall/table_windows_ntuser.c#L749 ?

**Comment by derekbruening** [comment]
xref "reactos update: NtUserGetClipboardFormatName: reactos now has this as LPWSTR instead of PUNICODE_STRING"

```
002f35ba ff15d4014100 call dword ptr [app_suite_tests!_imp__GetClipboardFormatNameW (004101d4)]

0:000> U poi( 004101d4)
USER32!GetClipboardFormatNameW:
76ca77fa 8bff             mov     edi,edi
76ca77fc 55               push    ebp
76ca77fd 8bec             mov     ebp,esp
76ca77ff 5d               pop     ebp
76ca7800 ebd8             jmp  USER32!NtUserGetClipboardFormatName (76ca77da)

int WINAPI GetClipboardFormatName(
  _In_  UINT   format,
  _Out_ LPTSTR lpszFormatName,
  _In_  int    cchMaxCount
);

pre-syscall:
0:000> dc 001afa54  
001afa54  01000000 001afa38 001afaa4 001afb44  ....8.......D...
001afa64  778c1a05 9f6db517 fffffffe 77921376  ...w..m.....v..w
001afa74  778db146 021c0000 50000163 77883cf3  F..w....c..P.<.w
post-syscall:
eax=00000016
0:000> dc 001afa54  
001afa54  004d0057 004d005f 004f0053 004f005f  W.M._.M.S.O._.O.
001afa64  00460046 00430049 00410045 00530053  F.F.I.C.E.A.S.S.
001afa74  00530049 00410054 0054004e 77880000  I.S.T.A.N.T....w
```

So the kernel wrote a null but did not include it in the size returned.
