### ISSUE TITLE
No 64-bit support, in this day and age?

### ISSUE THREAD

**Issue by farmdve** [DynamoRIO/drmemory#1841]
What are the reasons for this?

ERROR: failed to create process (err=720)

**Comment by derekbruening** [comment]
> What are the reasons for this?

Lack of manpower: not enough contributors.

Light mode does support 64-bit in recent builds (https://build.chromium.org/p/client.drmemory/builds/).

Dup of #111, #889

**Comment by farmdve** [comment]
Is there any ETA?

**Comment by derekbruening** [comment]
Light mode supports 64-bit already.  For full mode, contributions may be needed for support in the near future.

**Comment by derekbruening** [comment]
See https://github.com/DynamoRIO/drmemory/wiki/Contributing for information on how to contribute
