### ISSUE TITLE
Dr. Fuzz -fuzz_replace_buffer causes test failures

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/drmemory#1847]
Current implementation of the -fuzz_replace_buffer only change state->input_buffer and state->input_size, and it forgets to change the state->mutation_start, which is where the mutation value is copied too, so we should adjust the state->mutation_start accordingly.

It may also affect how we use the mutator because it stores the size of the input. Once we create the mutator, we should not use the same input buffer for that mutator.

**Comment by derekbruening** [comment]
Which tests fail?  The pre-commit suite has been passing for me, and the bots did not send email.

**Comment by zhaoqin** [comment]
my local test with different options combination, if you add -fuzz_replace_buffer to your fuzz_buffer test, it will fail.

**Comment by derekbruening** [comment]
So there is no test in the suite that passes -fuzz_replace_buffer?  The option was added with no test?

**Comment by zhaoqin** [comment]
There is a test with -fuzz_replace_buffer, just no test combine the -fuzz_replace_buffer with mutation and check the mutation value.
The -fuzz_replace_buffer was added for loading input files.
