### ISSUE TITLE
Semi false positive in SSE optimized wstrnlen functions - UNADDRESSABLE ACCESS

### ISSUE THREAD

**Issue by carpenterjc** [DynamoRIO/drmemory#1869]
With visual studio 2015 when you use the SSE2 optimized version of wcsnlen (commonly used by format string and printf) if the string doesn't end on an allocation boundary the SSE version common_strnlen will test beyond the length of the string. 

When you read the documentation in strnlen.cpp:116 it explicitly mentions why this occurs and why its not a problem. The function can decide under certain situations if the allocation starts on a memory boundary to use a the optimized version, if not on a boundary it will fallback.

Stack example with a string length of 53 characters:
Error #1: UNADDRESSABLE ACCESS beyond heap bounds: reading 0x0253dbe8-0x0253dbf0 8 
byte(s) within 0x0253dbe0-0x0253dbf0
0 common_strnlen_simd<>               [d:\th\minkernel\crts\ucrt\src\appcrt\string\strnlen.cpp:116]
1 common_strnlen<>                    [d:\th\minkernel\crts\ucrt\src\appcrt\string\strnlen.cpp:153]
2 wcsnlen                             [d:\th\minkernel\crts\ucrt\src\appcrt\string\strnlen.cpp:173]
3 MyTestApp                      [xxxxx]
4 main                                [xxxxx]
Note: @0:00:01.889 in thread 15944
Note: refers to 0 byte(s) beyond last valid byte in prior malloc
Note: prev lower malloc:  0x0253db68-0x0253dbe8
Note: instruction: movups (%edx) -> %xmm0

Secondary example:

Error #1: UNADDRESSABLE ACCESS beyond heap bounds: reading 0x00cde908-0x00cde910 8 byte(s) within 0x00cde900-0x00cde910
0 wcsnlen         [d:\th\minkernel\crts\ucrt\src\appcrt\string\strnlen.cpp:173] (0x013b55aa <xxxx.exe+0x155aa>) modid:1
1 __crt_stdio_output::output_processor<>::type_case_s [d:\th\minkernel\crts\ucrt\inc\corecrt_internal_stdio_output.h:2248] (0x013b3666 <xxx.exe+0x13666>) modid:1
2 __crt_stdio_output::output_processor<>::process [d:\th\minkernel\crts\ucrt\inc\corecrt_internal_stdio_output.h:1644] (0x013b2c57 <xxx.exe+0x12c57>) modid:1
3 __stdio_common_vswprintf [d:\th\minkernel\crts\ucrt\src\appcrt\stdio\output.cpp:247] (0x013b388e <xxx.exe+0x1388e>) modid:1
4 ATL::CStringT<>::FormatV [c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include\cstringt.h:2221] (0x013a3f95 <xxxx.exe+0x3f95>) modid:1

I have a workaround, but am worried about suppressing too much: 

UNADDRESSABLE ACCESS
*!common_strnlen_simd<>
*!common_strnlen<>

I am trying to get a simple reproduction, will follow when that is ready.

**Comment by derekbruening** [comment]
Xref #350.  We have replacements for most wide string routines but simply omitted a direct wcsnlen (we do have a wchar_t-typed strnlen replacement).
