### ISSUE TITLE
DrMemory needs to support ymm registers for VS 2015

### ISSUE THREAD

**Issue by randomascii** [DynamoRIO/drmemory#1872]
The VS 2015 Universal Windows 10 CRT uses ymm registers on CPUs that support them in some cases. For instance, wcsnlen of a sufficiently long string will use a sequence like this:

6E4D2F56  vxorps      ymm1,ymm1,ymm1  
6E4D2F5A  lea         ecx,[edx+ecx*2]  
6E4D2F5D  jmp         _wcsnlen+0AEh (6E4D2F6Eh)  
6E4D2F5F  vpcmpeqw    ymm0,ymm1,ymmword ptr [edx] 
6E4D2F63  vpmovmskb   eax,ymm0  
6E4D2F67  test        eax,eax  
6E4D2F69  jne         _wcsnlen+0B2h (6E4D2F72h)  

This comes from C:\Program Files (x86)\Windows Kits\10\Source\10.0.10586.0\ucrt\string\strnlen.cpp, in common_strnlen_simd. This definitely causes over-read warnings, and may also cause others.

Other failures that are suppressed in crrev.com/1814273002 are suspected to be AVX related, but not confirmed.

**Comment by derekbruening** [comment]
Duplicate:
+ Supporting ymm shadow propagation rather than reporting errors on uninits in ymm registers is #1485 
+ Replacing wcsnlen is #350 / #1869
