### ISSUE TITLE
Dr. Memory internal crash at PC 0x70f2e26b

### ISSUE THREAD

**Issue by BretVH** [DynamoRIO/drmemory#1890]
Program aborted.
0xc0000005 0x00000000 0x70f2e26b 0x70f2e26b 0x00000003 0x00000000
Base: 0x70e60000
Registers: eax=0x00000000 ebx=0x004ff498 ecx=0x6d8c6d54 edx=0x00000000
	esi=0x19f91030 edi=0x1a143a5c esp=0x004ff4b8 ebp=0x004ff56c
	eflags=0x000
1.10.1-3-(Apr 10 2016 18:06:45) win101
-no_dynamic_options -disasm_mask 8 -logdir 'F:\Dr. Memory\drmemory\logs\dynamorio' -client_lib 'F:\Dr. Memory\bin\release\drmemorylib.dll;0;-visual_studio -logdir `F:\Dr. Memory\drmemory\logs` -symcache_dir `F:\Dr. Memory\drmemory\logs\symcache` -lib_blacklist `C:\Windows*.d??,C:\Program Files (x86)\Common Files\Microsof
0x004ff56c 0x70f095fe
0x19f91024 0x19f71030
0x19fa5ac8 0x02d2bca0
0x19fa4fd4 0x02d34430
0x19fa7384 0x00000038
0x19f9add8 0xffffffff
0x19fa3fbc 0x00000030
0x19f99b1c 0x0000027b
0x19fa6af8 0x02d3437c
0x1a201024 0x00000005
0x1a62ec0c 0x00000813
0x1a6c151c 0x499fec17
0x1a150600 0x19fc5fe8
0x1a2ebb78 0x0000033e
0x1a2e48b8 0x02d37068>
         WARNING: application exited with abnormal code 0xffffffff

**Comment by zhaoqin** [comment]
Please provide more information about the crash, e.g., OS version, what the app does, etc.
Also, did you try the debug build, did you try the light version (-light, -leaks_only) etc.
Xref [debugging](https://github.com/DynamoRIO/drmemory/wiki/Debugging) page for preliminary debugging.

**Comment by derekbruening** [comment]
There's not enough info here to act on.  Closing the issue as CannotReproduce.
