### ISSUE TITLE
False positive in WaitNamedPipeW with NMPWAIT_USE_DEFAULT_WAIT.

### ISSUE THREAD

**Issue by akmistry** [DynamoRIO/drmemory#1891]
Very similar to https://github.com/DynamoRIO/drmemory/issues/1827.

DrMemory reports UNINITIALIZED READ when calling WaitNamedPipeW with NMPWAIT_USE_DEFAULT_WAIT:
```
Error #1: UNINITIALIZED READ: reading 0x01397cc8-0x01397cd0 8 byte(s) within 0x01397cc8-0x01397cd4
# 0 system call NtFsControlFile FILE_PIPE_WAIT_FOR_BUFFER Timeout+NameLength
# 1 KERNELBASE.dll!WaitNamedPipeW                                             +0x191    (0x74dc4732 <KERNELBASE.dll+0x54732>)
# 2 main
```

Sample code:
```
#include <windows.h>

int main() {
  BOOL ret = WaitNamedPipeW(L"\\\\.\\pipe\\doesnotexist", NMPWAIT_USE_DEFAULT_WAIT);
  return ret;
}
```

**Comment by akmistry** [comment]
I should have mentioned which version:
```
Dr. Memory version 1.10.16923 build 106703105 built on May  2 2016 11:49:35
```

**Comment by derekbruening** [comment]
You're saying that WaitNamedPipeW just leaves FILE_PIPE_WAIT_FOR_BUFFER.Timeout uninitialized?

**Comment by derekbruening** [comment]
Xref https://bugs.chromium.org/p/chromium/issues/detail?id=616564

**Comment by akmistry** [comment]
I'm not a windows developer, so I'm honestly not sure what's supposed to happen. But in the Chromium bug, a timeout is set when the pipe is created, and the call to WaitNamedPipeW always occurs after a call to CreateNamedPipeW.

**Comment by derekbruening** [comment]
There's a TimeoutSpecified field that indicates whether Timeout is meaningful.
