### ISSUE TITLE
Dr. Memory internal crash

### ISSUE THREAD

**Issue by paukonen** [DynamoRIO/drmemory#1893]
Hi! Dr.Memory keeps crashing when I'm trying to launch my applications with it.
I have tried all options from "Narrowing Down the Source of the Problem" guide, tried launching Dr.Memory on 64-bit Windows 8.1 and on 32-bit Windows 7. I changed my toolchain from msys/mingw32 to msys2/mingw-w64, but result is the same.

Sometimes, very rarely - in 1 case out of 50, Dr.Memory starts fine and shows proper results in the end. But it happens only with the most simple application with very small codebase. More complex applications always lead Dr.Memory to crash.

I also tried running DynamoRIO directly with my applications, and it works flawlessly.

Here is some data I collected:
![crash](https://cloud.githubusercontent.com/assets/7750429/15896052/2cf66dea-2d97-11e6-980b-177dac8c480d.png)
[results.txt](https://github.com/DynamoRIO/drmemory/files/304867/results.txt)
[global.12168.txt](https://github.com/DynamoRIO/drmemory/files/304864/global.12168.txt)

**Comment by paukonen** [comment]
Should I provide some additional information about this crash? Is it possible to investigate this problem?

**Comment by derekbruening** [comment]
Ideally, if you could provide the sources and build instructions for the smallest application that exhibits this problem along with which platform to run it on, we can try to reproduce.

**Comment by derekbruening** [comment]
There is not enough information to act on.  Closing as CannotReproduce.
