### ISSUE TITLE
Visual studio argument list size too small

### ISSUE THREAD

**Issue by svarjo** [DynamoRIO/drmemory#1895]
The argument list appears to be limited (to 256 characters?) with Visual Studio plugin. This is limiting the usability in our case. For example we have default command:
D:\DrMemory-Windows-1.10.1-3\bin\drmemory.exe

and Arguments:
-visual_studio -logdir d:/debug/ -show_reachable -conservative -syscall_sentinels -- $(TargetPath) $(our_arguments)

The $(TargetPath) alone is 86 chars long.  $(our_arguments) may contain also (multiple) paths and easily grows over 256 chars long. This yields to clipped initial calls such as:

D:\projects\Products\OurProductV_1\platforms\windows\Debug\OurProduct_v1_test1.exe -s=params123 -pA=p1 -pB=p2 -cC=p3 -pD=p4 -pE=p5 -pF=p6 d:\debug\input_a1.dat d:\debug\inpu" 

,where some input parameters (and output parameters are clipped). This makes the tool difficult to use.

**Comment by derekbruening** [comment]
This should be filed with the Visual Studio team if they really limit external tool command lines to 256 chars.  There may be nothing we can do about it except some kind of workaround like a file redirection option where you list your parameters in a file and then point at the file on the command line.  We would be happy to accept such a feature contribution.

**Comment by blueelvis** [comment]
I don't think that this is a problem inside VS. By default, the input stream is reserved till 256 characters. Just found an article over [here](https://msdn.microsoft.com/en-us/library/system.console.readline(v=vs.110).aspx) - 

> By default, the method reads input from a 256-character input buffer. Because this includes the Environment.NewLine character(s), the method can read lines that contain up to 254 characters. To read longer lines, call the OpenStandardInput(Int32) method.

This is for C# but I won't be surprised if this is the problem in this case ^_^.

**Comment by derekbruening** [comment]
Visual Studio is the one doing the reading of the arguments from the user in its dialog box.  There is zero code in Dr. Memory involved in this after registration: we simply register as an External Tool and Visual Studio is the one handling the interface.  Visual Studio creates the dialog boxes for user input and then creates a process that invokes Dr. Memory with the arguments from the user.
