### ISSUE TITLE
How to use DrMemory with complicated multiple thread server process?

### ISSUE THREAD

**Issue by MrMemoryW** [DynamoRIO/drmemory#1904]
Hi, 
I am trying to use DrMemory to check memory issues on my server.
The server has very complicated logic and runs in multi-thread mode. Generally, it listens on network events and accepts connections from clients, further it helps to switch data among different clients.
The server never exists unless I kill it with signal #15.
Now I am running my server with DrMemory and meet below issues:
1. I see warning message as below:

~~16222~~ WARNING: Unable to create symcache temp file /opt/webex/mmp/bin/DrMemory/DrMemory-Linux-1.10.1-3/drmemory/logs/symcache/libnuma.so.1.txt.0999.tmp
~~16222~~ WARNING: Unable to create symcache temp file /opt/webex/mmp/bin/DrMemory/DrMemory-Linux-1.10.1-3/drmemory/logs/symcache/libnque11.so.txt.0999.tmp
2. No memory checking result displayed on screen
3. The CPU of the server is not very high (about 10%), but it seems the network condition is bad when running with DrMemory
4. I don't know how to get memory information during running, I tried to kill my process with kill -15, but there was coredump generated and still no memory information

would you please help to solve those issues? Thanks!

**Comment by derekbruening** [comment]
General questions should be sent to the [users list](http://groups.google.com/group/DrMemory-Users): the issue tracker is for specific bugs found or for feature requests.

See http://drmemory.org/docs/page_running.html#sec_daemon for how to send a nudge to a daemon that does not exit.  Please ask further questions on the mailing list.
