### ISSUE TITLE
failed to find dbghelp.dll Windows 7/Visual Studio 2010 no SDK

### ISSUE THREAD

**Issue by mxmssh** [DynamoRIO/drmemory#1956]
C:\drmemory\build>cmake -G"Visual Studio 10" -DCMAKE_BUILD_TYPE=Debug ..\drmemory
-- Dr. Memory version number: 1.11.17239
-- Targeting subsystem 5.00
Looking: /bin/x86/dbghelp.dll/tools/tracing/i386/dbghelp.dllC:\Program Files/Microsoft Visual Studio */Common7/IDE/Remote Debugger/x86/dbghelp.dllC:\Program Files (x86)/Windows Kits/*/Debuggers/x86/dbghelp.dllC:\Program Files/Microsoft Visual Studio */Common7/IDE/dbghelp.dllC:\Program Files/Debugging Tools for Windows/dbghelp.dll
CMake Error at CMakeLists.txt:597 (message):
  dbghelp.dll required and not found

-- Configuring incomplete, errors occurred!
See also "C:/drmemory/build/CMakeFiles/CMakeOutput.log".

**Comment by mxmssh** [comment]
I'm trying to build 32bit executable in x64 OS.

**Comment by mxmssh** [comment]
there is dbghelp.dll 6.12.XXXX at C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\Remote Debugger\x86

**Comment by derekbruening** [comment]
Is this a regression from 0a37fb199363086967e00de4ac6f77316325fa34?  It works with the prior code?

**Comment by mxmssh** [comment]
Looks like that, I'm preparing new pull request to fix that.
