### ISSUE TITLE
Getting "Running on an unsupported operating system" on Windows 10 (v1703)

### ISSUE THREAD

**Issue by lordmulder** [DynamoRIO/drmemory#1976]
> Running on an unsupported operating system. Please download http://drmemory.org/syscalls_wow64.txt and save as C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt to avoid false positives and other problems. **If that fails, please file a bug report**.

So, here is the report 😉

I'm running Windows 10 64-Bit **v1703**, aka "Creators Update", aka OS Build 15063.13.

Updated "syscalls_wow64.txt" from the URL given above didn't help!

Regards.

**Comment by derekbruening** [comment]
I posted a new version of http://drmemory.org/syscalls_wow64.txt (similarly for x86 and x64).  I have done some testing but would appreciate help: does it make the warning and new false positives (seen when running with -ignore_kernel before but not there on Win10-1607) go away?

**Comment by lordmulder** [comment]
Thanks, the new "syscalls_wow64.txt" removes the warning. Didn't notice any False Positives so far.

Regards.

**Comment by PeterTaylor2** [comment]
I have just been upgraded to winver 1609 (OS Build 16299.19) and the syscalls_wow64.txt file that I downloaded is not working for me. I get the message: syscalls_wow64.txt does not contain an entry for this kernel.

**Comment by DesmondFox** [comment]
After Fall Creators Update I have an error about syscalls_wow64.txt.

**Comment by derekbruening** [comment]
This issue is about 1703.  1709 is #2060.  Hope to have an updated file there soon.  (If anyone knows of Windows devs who would like to contribute to the project we could use the help.)

**Comment by derekbruening** [comment]
a8eea64f66daa5394226981800972a31dd495671 adds built-in 1703 support so I'm closing this.

**Comment by derekbruening** [comment]
For those monitoring this issue rather than #2060 I'm duplicating the message here:

I posted new text files including syscalls_wow64.txt for Windows 10 1709. Local tests look good but please try the files out and report any problems in #2060.

**Comment by PeterTaylor2** [comment]
the new text file works well - thank you very much for your prompt response

**Comment by Trontor** [comment]
Hi! I'm getting this issue aswell.

**Comment by derekbruening** [comment]
> Hi! I'm getting this issue aswell.

You mean you have 1703 and you have the new syscalls*.txt file in place and still get the unsupported message?

**Comment by Trontor** [comment]
Sorry for lacking details, I have the txt file in place, and this my system details:

OS Name	: Microsoft Windows 10 Home
Version	: 10.0.17134 Build 17134

I am still getting the unsupported message. Not sure why.

**Comment by derekbruening** [comment]
17134 is 1803 which is not this issue which is about 1703.  You want #2102.
