### ISSUE TITLE
Print module id + offset for return address in drltrace

### ISSUE THREAD

**Issue by mxmssh** [DynamoRIO/drmemory#1979]
We have to print a module id + offset for return addresses in drltrace instead of an absolute address which we use now and provide a list of modules at the end of execution to translate the module ids to paths.

**Comment by Clcanny** [comment]
May I ask that:
Is the ret addr you mentioned == the return address of sys-call?

**Comment by mxmssh** [comment]
yes, ret address is the return address of system call or library call.

**Comment by Clcanny** [comment]
thank u very much!!! You are so nice.
And I would like to ask one more question:
```c
static void
lib_entry(void *wrapcxt, INOUT void **user_data)
{
    const char *name = (const char *) *user_data;
    const char *modname = NULL;
    app_pc func = drwrap_get_func(wrapcxt);
    ....
}
```
Is the variable `func` == the entry address of the function which make the sys-call?

**Comment by mxmssh** [comment]
It's not clear what is `f` in our example. Is it some function from shared library or just a function in a standalone executable ? 
In general, `drwrap_get_func` returns the address of the wrapped function represented by `wrapcxt`. So, it's an address of library call from wrapped shared library loaded in the process that we instrument. So, if we have some `hello_world.exe` that loads `kernel32.dll` (Windows system library), we will report all library calls to kernel32.dll.
For example if some function `f` from `hello_world.exe` calls [CreateFileA](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx) from kernel32.dll 
```
void f()
{
    CreateFileA(some_args)
}
```
We will have an address of `CreateFile `in the `func` but we don't know anything about `f`.

**Comment by Clcanny** [comment]
The answer is perfect.
Thank you very much!!!!!
I am going to follow you and star your projects!!

**Comment by mxmssh** [comment]
Thank you.
