### ISSUE TITLE
Crash on jpeg_finish_decompress with drmemory!

### ISSUE THREAD

**Issue by Karaulov** [DynamoRIO/drmemory#1981]
Crash on jpeg_finish_decompress with drmemory! Without drmemory - no crash.

Deleaker too have this problem. (I try to use trial Deleaker stanalone version, too crash in jpeg_finish_decompress  function as and drmemory)

**Comment by Karaulov** [comment]
JPEG lib, latest source code, builded in visual studio 2017: 

http://rgho.st/private/8572bBNPB/916e7b96742110124aedac3a576e5aa9 
Here code: 
https://pastebin.com/Y5Rm9xxr  // crash when read jpeg to raw buffer
( and buffer.h https://pastebin.com/JFd9dYZ8 )

**Comment by Karaulov** [comment]
Impossible to fix this error in drmemory ?

**Comment by derekbruening** [comment]
What are the details on the crash?  Does the application crash and an application fault handler or Windows itself reports it, or does Dr. Memory report it?

What platform is this -- operating system & version, architecture, bitwidth?

Did you try the steps at https://github.com/DynamoRIO/drmemory/wiki/Debugging "Narrowing Down the Source of the Problem"?  What are the results for each step?

**Comment by derekbruening** [comment]
What version of Dr. Memory?

**Comment by Karaulov** [comment]
possible this my mistake.
