### ISSUE TITLE
Update drstrace and drltrace to use auto-generated syscall number files

### ISSUE THREAD

**Issue by emmanueltsukerman** [DynamoRIO/drmemory#1983]
I have a fresh installation of Dr. Memory on a Windows 10 VM. When I run
bin\drstrace -- calc
and
bin64\drstrace -- calc
in cmd with administrator privilege I receive the error
ASSERT FAILURE: D:\drmemory_package\drstrace\drstrace.c:670: false (drsys failed to init)
and no output is produced.

**Comment by derekbruening** [comment]
Unfortunately "Windows 10" doesn't tell us enough as its updates are major despite still being called "Windows 10": is this the just-out "Creators Update" 1703?

If so, and the return value from drsys_init is DRMF_WARNING_UNSUPPORTED_KERNEL, this is not surprising.  We should put the error message and syscall text file support that Dr. Memory uses from #1908 (xref e81c1cd9d16aa38e2efaf1650fb9590c31d67e84) into drstrace to support major Windows updates with just a data file update.

**Comment by emmanueltsukerman** [comment]
Yes, it is the new update:
Windows 10 Enterprise Evaluation
Version 1703
OS Build 15063.138

I see only the assertion bug; no additional output is given (see image).
![drstract_assert_failure](https://cloud.githubusercontent.com/assets/23566736/25396725/7d7e3054-299a-11e7-9ba2-8258923f6829.png)

I've placed the syscalls file in bin64
![drstrace_syscallsfile](https://cloud.githubusercontent.com/assets/23566736/25396821/e9c93f38-299a-11e7-82b5-bdfaaaa843d0.png)

**Comment by derekbruening** [comment]
Right, but we never put the support into drstrace to read the syscall file: unfortunately it is only in drmemory right now.

Putting a note into #1848 to include drstrace (and drltrace) in the solution there as well.

**Comment by emmanueltsukerman** [comment]
Thanks for the quick reply. 
1. Do you have any recommendations on work-arounds? Are the only two feasible options to rewind the windows update or wait for the fix?
2. Do you have an estimate on how long it will take to fix the issue (on the order of days, weeks or months?)

**Comment by DarkHunterer** [comment]
Up,

is there anything we can do to make drstrace work on Windows 10?
If not, would you recommend any other solution to trace Windows API calls?

**Comment by derekbruening** [comment]
You could take a stab at pointing to the syscall text file when drstrace initializes drsyscall, which is not much code: see the patch to drmemory/syscall.c from e81c1cd9d16aa38e2efaf1650fb9590c31d67e84

**Comment by DarkHunterer** [comment]
I was willing to do that but unfortunately I am not able to succesfuly build this project with command line on Windows

**Comment by newgre** [comment]
I have the same problem - drstrace fails with above error. Using 64bit Windows 10: Microsoft Windows [Version 10.0.15063]

**Comment by AlexanderSamoilov** [comment]
The Windows build for the version 1.11.17622-1 available at https://github.com/DynamoRIO/drmemory/releases/download/cronbuild-1.11.17622/DrMemory-Windows-1.11.17622-1.zip does not contain this issue. Tested today on Windows 10 64bit.

**Comment by vjardin** [comment]
The problem still occurs with this build:
C:\Program Files (x86)\Dr. Memory\bin64>drstrace.exe -version
Dr. Memory drstrace version 1.11.17622 -- build 1

C:\Program Files (x86)\Dr. Memory\bin64>drstrace.exe -- calc.exe
WARNING: fetching symbol information (procedure may take some time).
WARNING: symbol fetching failed.  Symbol lookup will be disabled.
ASSERT FAILURE: ..\..\drstrace\drstrace.c:670: false (drsys failed to init)
C:\Program Files (x86)\Dr. Memory\bin64>

PS C:\Users\vjard> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0

**Comment by AlexanderSamoilov** [comment]
This sound strange, because for me this version works fine. Perhaps, it depends not only on the Dr.Memory version?

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\asa>C:\Tools\DrMemory-Windows-1.11.17622-1\bin64\drstrace.exe -version
Dr. Memory drstrace version 1.11.17622 -- build 1

C:\Users\asa>C:\Tools\DrMemory-Windows-1.11.17622-1\bin64\drstrace.exe -- calc.exe
WARNING: fetching symbol information (procedure may take some time).
WARNING: symbol fetching failed.  Symbol lookup will be disabled.
<drstrace log file is .\drstrace.calc.exe.12300.0000.log>

C:\Users\asa>echo %ERRORLEVEL%
0
```

**Comment by vjardin** [comment]
Yours is 10.0.15063
Mine is 10.0.17134.165

What could I do to gather proper logs during init ?

**Comment by derekbruening** [comment]
The future plan is to use auto-generated syscall numbers via #1848 rather than relying on tables.  This is already in Dr. Memory 2.1.0.  This issue covers changing drstrace to use auto-generated syscall number files.

**Comment by derekbruening** [comment]
The fix didn't make it for the July 5 cronbuild.  It will be in the July 12 cronbuild.
