### ISSUE TITLE
DynamoRIO crashes at startup on Ubuntu

### ISSUE THREAD

**Issue by techvoltage** [DynamoRIO/drmemory#1992]
Command:
bin64/drrun -debug -loglevel 4 -c api/bin/libinstrace_simple.so -- ls

Build:
drrun version 6.2.17301 -- build 0
[Build Steps](https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build
)

Machine:
Linux  4.4.0-31-generic #*50*~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 
GNU/Linux

Log:
[ls.0.26129.txt](https://github.com/DynamoRIO/drmemory/files/1009963/ls.0.26129.txt)

**Comment by derekbruening** [comment]
Why is this filed in the Dr. Memory tracker?  Probably best to file in the DynamoRIO tracker, and provide more information there: Does this only happen with the instrace_simple client?  What happens with no client at all?  What is the output from the command?

**Comment by techvoltage** [comment]
Issue refiled at https://github.com/DynamoRIO/dynamorio/issues/2438
