### ISSUE TITLE
Umbra does not import libc

### ISSUE THREAD

**Issue by toshipiazza** [DynamoRIO/drmemory#1993]
When running a simple app in debug mode, I see the following message:

```
$ drrun -debug -c ./umbra_app.so -- ../foo-c
...
<Starting application /home/piazzt/XXX/foo-c (91698)>
<WARNING! symbol lookup error: libumbra.so undefined symbol memchr>
```

Indeed, `memchr` is used in `umbra_value_in_shadow_memory_arch` in both `umbra_{x86,x64}.c`. It looks like the following patch silences this error:

```diff
diff --git a/umbra/CMakeLists.txt b/umbra/CMakeLists.txt
index b211b1b..9da4481 100644
--- a/umbra/CMakeLists.txt
+++ b/umbra/CMakeLists.txt
@@ -27,11 +27,6 @@ if ("${CMAKE_VERSION}" VERSION_EQUAL "2.8.12" OR
   cmake_policy(SET CMP0022 OLD)
 endif ()
 
-# We do not need libc, and we avoid a 10x size increase in both our
-# dll and pdb (plus we avoid stressing private library isolation) by
-# not using it (i#714).
-set(DynamoRIO_USE_LIBC OFF)
-
 set_output_dirs(${framework_bindir})
 
 set(srcs
```

Is this comment ("We do not need libc...") in error and is the patch appropriate? Or should we just copy over an implementation of `memchr` into `dr_memchr` and then use that instead?

**Comment by derekbruening** [comment]
I think the comment is incorrect.  At a quick glance I also see memcpy, memmove, memset undefined in libumbra.so as well.
