### ISSUE TITLE
No(or far fewer)  leaks are found on windows 10

### ISSUE THREAD

**Issue by bxantus** [DynamoRIO/drmemory#2010]
We discovered an anomaly today on our project.
We are running dr memory for our unit tests (using gtest framework), and there is a difference in the results on my pc (running windows 7) and on other people's machine (running windows 10).

The leaks found on my machine were all valid findings. None of them was found on the windows 10 machines. We did run the same version of dr. memory (1.11.0 build 2 built on Aug 29 2016 02:42:07) for the same executable.

I made a diff on the resulting logs, and the windows 10 versions had a few warnings about operator new and operator delete. Could this cause the issue?

Here are the warnings:
```
module load event: "TestAPI.exe" 0x01290000-0x029d4000 modid: 1 c:\_HG\work\Win32\debug\Develop\TestAPI.exe
WARNING: unknown 3+-arg overload of operator new in TestAPI.exe @0x01b0dbc0
WARNING: unknown 3+-arg overload of operator delete in TestAPI.exe @0x01b0de10
WARNING: unknown 2-arg overload of operator delete[] in TestAPI.exe @0x025a11d0
WARNING: unable to determine type of operator delete[] in TestAPI.exe @0x025a11d0
WARNING: unknown 2-arg overload of operator delete in TestAPI.exe @0x025a0140
WARNING: unable to determine type of operator delete in TestAPI.exe @0x025a0140

...

module load event: "MSVCP140D.dll" 0x5b7c0000-0x5b879000 modid: 4 C:\Windows\SYSTEM32\MSVCP140D.dll
WARNING: unknown 2-arg overload of operator delete in MSVCP140D.dll @0x5b838ed0
WARNING: unknown 2-arg overload of operator delete[] in MSVCP140D.dll @0x5b8397e0
```

None of these were found in my logs.

Of course it could be that the issue has an other root cause, but we did not find any difference between the two environments, except the OS.

Let me know if you need anything else, to help investigate this issue.

**Comment by derekbruening** [comment]
Identifying the new/delete operator variants mostly affects the delete vs delete[] mismatch errors, not leaks.  Could you provide further information on the leaks?  If possible, a small program that reproduces the leak discrepancy would be perfect.

**Comment by bxantus** [comment]
Thanks for the feedback!
Sorry for the delay, we hadn't have time recently to investigate this issue further. 
delete vs. delete[] errors weren't reported in either case (probably we didn't have those).

We'll try to reproduce the issue in a simple app with or without the gtest framework, and will post the updates here.
