### ISSUE TITLE
drsym_lookup_address crash my application

### ISSUE THREAD

**Issue by Clcanny** [DynamoRIO/drmemory#2013]
I try to modify drltrace.cpp to let it tell me the symbol name of the return address.

```c
drsym_info_t sym;
char name[50];
char file[50];
sym.struct_size = sizeof(sym);
sym.name = name;
sym.name_size = 50;
sym.file = file;
sym.file_size = 50;
```

```c
symres = drsym_lookup_address(mod_path, ret_addr - mod_start, &sym, DRSYM_DEMANGLE | DRSYM_DEMANGLE_PDB_TEMPLATES);
if (symres == DRSYM_SUCCESS || symres == DRSYM_ERROR_LINE_NOT_AVAILABLE)
{
	dr_fprintf(outf, "\nreturn tos %s\n", symbol->name == NULL ? "<null>" : symbol->name);
}
```

but i get Dr.LTrace internal crash at PC 0x5b2e745c. Please report this as ... Program aborted.
Do anyone know why and how to fix that?
Thanks.

**Comment by derekbruening** [comment]
Typical debugging steps:

- Run debug build

- Get a callstack for the crash point

**Comment by Clcanny** [comment]
When I build with debug, I only get this:
dynamorio\core\win32\callback.c:3730

```c
instr_get_opcode(&instr) == OP_lea &&
(opnd_get_disp(instr_get_src(&instr, 0)) == 0x10 ||
opnd_get_disp(instr_get_src(&instr, 0)) == 0x2dc)
```

but drmemory don't show the call stack.

**Comment by derekbruening** [comment]
Use a debugger to get the call stack.  See https://github.com/DynamoRIO/drmemory/wiki/Debugging and https://github.com/DynamoRIO/dynamorio/wiki/Debugging

**Comment by Clcanny** [comment]
The windbg is so hard to use, I don't know how to let it stop at a function(such as libentry).
I do this on win10.1703, is there another way?
I am trying to use windbg....

**Comment by derekbruening** [comment]
Attach at the crash point (pass "-msgbox_mask 12" to DR) and get the callstack there after loading the symbols as described on the wiki.
