### ISSUE TITLE
Auto-predication in DrMemory

### ISSUE THREAD

**Issue by toshipiazza** [DynamoRIO/drmemory#2039]
On my chromebook, almost all of the tests are failing, with the following error: `Usage error: auto-predication does not support cti's`

These failures are due to dynamorio/dynamorio#1723, since we updated the DynamoRIO submodule. For now we should globally disable auto predication in all insertion events in the repo.

**Comment by derekbruening** [comment]
Hmm, we used to have an ARM CDash bot to let us know when we broke things, but that disappeared...

**Comment by derekbruening** [comment]
I filed #2040 on (re)setting up ARM automated tests.

**Comment by toshipiazza** [comment]
Noted. It seems *after* we globally opt out of auto predication, we see the following errors everywhere:

```
~~Dr.M~~ ASSERT FAILURE (thread 1777): /home/piazzt/Build/drmemory/drmemory/replace.c:1139: false (Not Yet Implemented)
```

I can place a fix for the auto-predication stuff, but I don't have any experience with the replace code. Should I file another issue for this replacement assert afterwards?

**Comment by derekbruening** [comment]
Did your ARM machine update its libc recently?  That assert seems like it should not be triggered just on changes in DR, but that instead ARM libc now has indirected exports.  Yes, please file a separate issue.
