### ISSUE TITLE
Unable to build DrMemory on Ubuntu Linux x64

### ISSUE THREAD

**Issue by mxmssh** [DynamoRIO/drmemory#2057]
Found the following problem when building DrMemory on Ubuntu Linux x64:

CMake Error at tests/CMakeLists.txt:531 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "syscalls_unix".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.

**Comment by derekbruening** [comment]
I suspect this is not related to Ubuntu but is just dependent on your version of cmake?

**Comment by mxmssh** [comment]
Probably yes because I am using a new version of cmake 3.2.2. which is not officially supported.

**Comment by Faq** [comment]
Then why issue not closed?

**Comment by derekbruening** [comment]
Looks like a duplicate of #2049
