### ISSUE TITLE
Error "Running on an unsupported operating system" on Windows 10 (v1709)

### ISSUE THREAD

**Issue by wulfgarpro** [DynamoRIO/drmemory#2060]
> Dr. Memory version 1.11.0 build 2 built on Aug 29 2016 02:42:07
Dr. Memory results for pid 6508: "ConsoleApplication1.exe"
Application cmdline: "ConsoleApplication1.exe"
Recorded 115 suppression(s) from default C:\Program Files (x86)\Dr. Memory\bin\suppress-default.txt
C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt does not contain an entry for this kernel.
Running on an unsupported operating system. Please download http://drmemory.org/syscalls_wow64.txt and save as C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt to avoid false positives and other problems. If that fails, please file a bug report. Re-run with -ignore_kernel to attempt continued execution.

I've downloaded the latest syscalls_wow64.txt as recommended, but that didn't help.

Windows Specifications:

>Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.19

Running with `-ignore_kernel` flag results in the same errors.

> Dr. Memory version 1.11.0 -- build 2

**Comment by nkrepo** [comment]
The syscalls_wow64.txt needs to be updated to support Windows 10 Version 1709 unfortunately. I tested with `-ignore_kernel` on Windows 10 Version 1709, it reports the error but it proceeds.

**Comment by derekbruening** [comment]
I posted new text files including syscalls_wow64.txt for Windows 10 1709.  Local tests look good but please try the files out and report any problems.

**Comment by flythereddflagg** [comment]
The updated file seems to have fixed my problem.

**Comment by r3vival** [comment]
Yep fixed it for me too!
