### ISSUE TITLE
Dead link on "Latest Build" wiki page

### ISSUE THREAD

**Issue by devinacker** [DynamoRIO/drmemory#2062]
The link under "Builds for Recent Commits" on the project wiki points to [a page](http://build.chromium.org/p/client.drmemory/builds/) which no longer exists.

Are up-to-date development builds for Windows still provided somewhere?

**Comment by derekbruening** [comment]
> Are up-to-date development builds for Windows still provided somewhere?

Unfortunately not: new Windows contributors are needed to set something up, likely through Appveyor: #1967.

**Comment by derekbruening** [comment]
Link should be https://github.com/DynamoRIO/dynamorio/issues/1967 (in DR repo, not DrM, but setup would be shared or very similar)

**Comment by derekbruening** [comment]
There are now weekly "cronbuilds" at https://github.com/DynamoRIO/drmemory/releases
The links on the wiki are updated.

**Comment by devinacker** [comment]
Excellent, thank you!
