### ISSUE TITLE
Issues running DrMemory

### ISSUE THREAD

**Issue by CptMurrica** [DynamoRIO/drmemory#2076]
Hi, I am having issues running DrMemory. When trying to run it, I get the same error every time.

Application C:\Users\joshd\Documents\CS162\LittlePersonComputer\prog.exe (4916).  Dr. Memory internal crash at PC 0x6f68e36b.  Please report this at http://drmemory.org/issues.  Program aborted.
0xc0000005 0x00000000 0x6f68e36b 0x6f68e36b 0x00000001 0x00000000
Base: 0x6f5c0000
Registers: eax=0x00000000 ebx=0x0061f860 ecx=0xc72a1b74 edx=0x00000000
        esi=0x203a8930 edi=0x205a6c80 esp=0x0061f880 ebp=0x0061f930
        eflags=0x000
1.11.0-2-(Aug 29 2016 02:42:07) win102
-no_dynamic_options -disasm_mask 8 -logdir 'C:\Users\joshd\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\release\drmemorylib.dll;0;-logdir `C:\Users\joshd\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\joshd\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\WINDOWS*.d
0x0061f930 0x6f6693fe
0x203a8928 0x20401030
0x20423a70 0x00040003
0x206e0d20 0x00055980
0x205a80d4 0x00010001
0x205d7640 0x6f4b7440
0x206c25f4 0xffffffff
0x206be7c0 0xffffffff
0x206cdac8 0x6e694c2f
0x206c0590 0x00000038
0x206c15e8 0xffffffff
0x206bfa5c 0x0000002f
0x205d86fc 0x0000027c
0x2058e678 0x6f4b437c
0x206bf65c 0x0000008b

Any ideas?

**Comment by derekbruening** [comment]
What was the resolution?

**Comment by CptMurrica** [comment]
My teacher showed his workaround that managed to solve my issue. Apparently, the version of g++ that was bundled with QT Creator was giving me issues, so I installed the x86_64 version of g++ and compiled with that instead of the i686 version that came bundled.
