### ISSUE TITLE
syscalls_wow64.txt requires update for windows 10 v1803 build 17134.18 (April Update)

### ISSUE THREAD

**Issue by nkrepo** [DynamoRIO/drmemory#2102]
syscalls_wow64.txt requires update for windows 10 v1803 build 17134.18 (April Update).

**Comment by Deniskore** [comment]
**+1 Please update syscall table**

**Comment by derekbruening** [comment]
Hopefully #1848 will be finished before the next win10 major update

**Comment by derekbruening** [comment]
I placed syscalls_wow64.txt, syscalls_x64.txt, and syscalls_x86.txt updated for Win10 1803 at 
http://drmemory.org/

Leaving issue open for code changes for the next release

**Comment by nkrepo** [comment]
@Deniskore , Thank you for the update, looking forward for the #1848 .

**Comment by Deniskore** [comment]
@derekbruening is it normal?
`Syscall mismatch detected.  Running on unknown kernel version!
new thread #0 id=10852
`
Windows version 10.0.**17134**.48

**Comment by derekbruening** [comment]
Table is based on:
```
% strings -el /c/windows/system32/ntdll.dll | grep -A 1 FileVer
FileVersion
10.0.17134.1 (WinBuild.160101.0800)
```

You're saying 17134.48 has different numbers?  What's different?
