### ISSUE TITLE
drmemory on WIN 10 /1709

### ISSUE THREAD

**Issue by f10hn** [DynamoRIO/drmemory#2111]
I need a syscalls_wow64.txt for WIN 10 /1709 instead of 1803.
My application is running under drmemory but the results differ from running without drmemory.

**Comment by derekbruening** [comment]
1709 is issue #2060.  The latest syscalls_wow64.txt includes all versions through 1803, including 1709.  Please provide details (exact command line and output) exhibiting the problem.

**Comment by f10hn** [comment]
Hallo Derek,

you are right, the syscalls_wow64.txt is not the problem.

The following small C++-program shows, that there is a problem for drmemory with numeric calculation after throwing an exception:

(the program calculates 1/(1+0.0175) - after the exception the last bit of the result is false, if running with drmemory. I convert the double to unsigned long long for exact output).

I hope this is helpful for you. If you have more question, please ask.

Frank


#include <iostream>

static unsigned long long Dbl2ll(double dIn)
{
   unsigned long long * pllVal = (unsigned long long *)&dIn;
   return * pllVal;
}

static double ll2Dbl(unsigned long long lln)
{
   double *pdVal = (double *)&lln;
   return * pdVal;
}

 

int main()
{
   short sRc    = 2;
   unsigned long long llZinsvek = 4580701252991078893; 
   double dTest = ll2Dbl(llZinsvek); // dTest = 0.0175 
   printf("Output main: %llu\n",Dbl2ll(1./(1.+dTest)));
   try
   {
      if (sRc!=0)
         throw std::invalid_argument("Test"); //always thrown
   }
   catch (std::invalid_argument &)
   {
      printf("Output main catch: %llu\n",Dbl2ll(1./(1.+dTest)));
      return 0;
   }
}

this is the output:

D:\n-SL\ws_cor_win10\BFS_20180815_2002\buctr>C:\old\DrMemory\bin\drmemory.exe   -batch -- buctr
~~Dr.M~~ Dr. Memory version 1.11.17622
~~Dr.M~~ Running "buctr"
Output main: 4607027503825120142
Output main catch: 4607027503825120143   <---- error!
~~Dr.M~~
~~Dr.M~~ NO ERRORS FOUND:
~~Dr.M~~       0 unique,     0 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~       2 unique,     2 total,   4110 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: C:\old\DrMemory\drmemory\logs\DrMemory-buctr.exe.2668.000\results.txt

 

D:\n-SL\ws_cor_win10\BFS_20180815_2002\buctr>buctr
Output main: 4607027503825120142
Output main catch: 4607027503825120142  <----- correct

 

Am 22.08.2018 um 17:21 schrieb Derek Bruening:
> 1709 is issue #2060 <https://github.com/DynamoRIO/drmemory/issues/2060>. 
> The latest syscalls_wow64.txt includes all versions through 1803, 
> including 1709. Please provide details (exact command line and output) 
> exhibiting the problem.
> 
> —
