### ISSUE TITLE
Unsupported OS and syscalls_wow64.txt

### ISSUE THREAD

**Issue by Colelegante** [DynamoRIO/drmemory#2116]
So just got this error
`~~Dr.M~~ C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt does not contain an entry for this kernel.
~~Dr.M~~ Running on an unsupported operating system. Please download http://drmemory.org/syscalls_wow64.txt and save as C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt to avoid false positives and other problems. If that fails, please file a bug report. Re-run with -ignore_kernel to attempt continued execution.
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff`

I downloaded the new txt file and put it in the folder but it kept giving me the unsupported kernel error. Where can I download the newest syscalls_wow64.txt from?

**Comment by derekbruening** [comment]
#2102 put in files for 1803.
Please specify your Windows 10 version.

**Comment by Colelegante** [comment]
Yeah I have 1803. I've seen #2102 before but I cant find the place in the http://drmemory.org/ website to download the newer syscalls_wow64.txt.

**Comment by derekbruening** [comment]
http://drmemory.org/syscalls_wow64.txt

**Comment by Colelegante** [comment]
Huh, still gives me the same problem. Says the kernel that I'm using is unsupported.

I'm compiling from the Developer Command Prompt for VS2017 with this:
`cl /W4 /WX /Zi /MT /EHsc /Oy- /Ob0 /Fems.exe driver-sample.cpp List.cpp`
and this to run dr memory
`drmemory -batch -no_summary -- ms.exe`

**Comment by derekbruening** [comment]
What is your OS build number?

Could you check what the system call number for NtGetContextThread is?  If you have windbg, run `U ntdll!NtGetContextThread`; or disassemble it in whatever debugger you normally use.  What is the number stored in `eax`?

**Comment by Colelegante** [comment]
My OS build number is 17134.228
I'm not sure I understand what you are asking for in the second paragraph.

**Comment by derekbruening** [comment]
Are you sure you successfully wrote syscalls_wow64.txt to `C:\Program Files (x86)\Dr. Memory\bin`?  Windows has a file virtualization feature where non-elevated writes are redirected and appear to succeed but actually write to your profile dir.  You probably need to copy it there as admin.  (Future versions will relocate this file to avoid this permissions issue, and try to auto-generate it: #1848.)

**Comment by Colelegante** [comment]
Man thank you so much. That was exactly the problem. Now everything works fine. Thanks again :)

**Comment by derekbruening** [comment]
Good to hear.
