### ISSUE TITLE
Program crashes when run with drmemory

### ISSUE THREAD

**Issue by nico-abram** [DynamoRIO/drmemory#2119]
I just tried running https://github.com/etternagame/etterna/releases with drmemory. It crashes after loading. When run with 
```drmemory -report_leak_max -1 -leaks_only -no_count_leaks -no_track_allocs```
however it works. Any help is appreciated

EDIT:
I played around with the command line options and this crashed drmemory:
```
drmemory -leaks_only -no_check_uninitializ ed -no_check_gdi -no_check_prefetch -no_check_handle_leaks
```
![image](https://user-images.githubusercontent.com/24706838/45338632-8525bc80-b564-11e8-9683-97ddd0e162ac.png)

**Comment by derekbruening** [comment]
Please try the latest "cronbuild": https://github.com/DynamoRIO/drmemory/releases/tag/cronbuild-1.11.17785

Please try `-debug -dr_debug` to see if there are any diagnostic messages

Xref https://github.com/DynamoRIO/drmemory/wiki/Debugging

**Comment by nico-abram** [comment]
https://slexy.org/view/s2exCJHMMH

**Comment by nico-abram** [comment]
Edit:
I managed to run after changing the program's code. There was a section of it which checked if the program was already running to now allow multiple instances of the program. Allowing them made drmemory work. However it was still crashing but running with 
```
drmemory -leaks_only -no_check_uninitialized -no_check_gdi -no_check_prefetch -no_check_handle_leaks -light
```
Made it work. Thanks, and sorry. I think you can close this
