### ISSUE TITLE
Please make a Windows build for version 2?

### ISSUE THREAD

**Issue by Ben136KBC** [DynamoRIO/drmemory#2121]
I have used version 1.11.0-2 on the downloads page for Windows with good results on massive applications. Version 2 has been out for some time, but the downloads page still says "Windows will be available soon."

I realize that building it for Windows is non trivial (I looked), but this is really a great useful tool.

Please please please make an updated Windows version installer available?

**Comment by derekbruening** [comment]
Thank you for your interest.  Version 2 is supposed to have 64-bit full mode support, which was much easier to implement for Linux.  Windows is still missing solid 64-bit full mode support (#111), has callstack issues (#2064), and struggles with the Windows 10 "new major update (as major to Dr. Memory as Win8.1 to Win10) every 6 months" (#1848 needed).  Once those are done Windows will be ready for Version 2.  More developers would help: if you know someone who could contribute that would speed things up.

You can use a "cronbuild" at https://github.com/DynamoRIO/drmemory/releases to get a more recent Windows zip build but 64-bit full mode is not enabled by default.
