### ISSUE TITLE
Umbra special block protection is shifted and overflows the block

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/drmemory#2128]
https://github.com/DynamoRIO/drmemory/blob/6699e1bf92c7246770911a3affa7d6977049f985/umbra/umbra_32.c#L165

Perhaps I am reading the code incorrectly and my apologies if this is the case.

From my understanding, the setting of the _start_ param for the dr_memory_protect() call is incorrect. _block_ is incremented in _shadow_table_init_redzone()_ to refer to the shadow block skipping the upper redzone. However, the set size of the function call is that in **map->shadow_block_alloc_size**, which also includes redzone sizes. Consequently, the upper redzone of the shadow block is not being protected. Does anyone agree?

I will try and program a quick check to test my suspicion.

**Comment by derekbruening** [comment]
My reading agrees with you: it's protecting off the end and not protecting the pre-redzone.
