### ISSUE TITLE
Update documentation for preparing application

### ISSUE THREAD

**Issue by albertony** [DynamoRIO/drmemory#2159]
In Dr. Memory documentation's chapter about preparing Visual Studio (http://drmemory.org/docs/page_prep.html#sec_prep_windows):

>Additionally, under "Configuration Properties | Linker | Debugging", the "Generate Debug Info" entry should say "Yes (/DEBUG)". For Visual Studio 2015, under "Configuration Properties | Linker | Debugging", the "Generate Debug Info" entry should say "Optimize for debugging (/DEBUG)" – it should not say "Optimize for faster linking (/DEBUG:FASTLINK)".

I suggest appending a note for VS2017:
>For Visual Studio 2017 it should say "Generate Debug Information optimized for sharing and publishing (/DEBUG:FULL)".

Ref. documentation of linker options in Visual Studio 2017 (https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=vs-2017):
>When you specify /DEBUG with no additional options, the linker defaults to /DEBUG:FULL for command line and makefile builds, for release builds in the Visual Studio IDE, and for both debug and release builds in Visual Studio 2015 and earlier versions. **Beginning in Visual Studio 2017, the build system in the IDE defaults to /DEBUG:FASTLINK when you specify the /DEBUG option for debug builds**. Other defaults are unchanged to maintain backward compatibility.

**Comment by derekbruening** [comment]
Thank you for the update!
