### ISSUE TITLE
assertion failure: load2x of 8-byte memop not supported

### ISSUE THREAD

**Issue by daniel-starke** [DynamoRIO/drmemory#2183]
```
Application D:\Program Files\xxx\xxx.exe (2088).  Dr. Memory internal crash at PC 0x00000000026416df.  Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'.  Program aborted.
0xc0000005 0x00000000 0x00000000026416df 0x00000000026416df 0x0000000000000000 0x0000002000f4d3f0
Base: 0x0000000071000000
Registers: eax=0x0000000055555555 ebx=0x0000000003d34fc0 ecx=0x00000000000034fc edx=0x0000000000000004
	esi=0x0000000000000000 edi=0x00000000296ce301 esp=0x00000000296cdf60 ebp=0x0000000000000000
	r8 =0x0000000000000010 r9 =0x0000002000f40000 r10=0x0000000003d00000 r11=0x0000000000f40000
	r12=0x0000000003d35fbc r13=0x0000000000000001 r14=0x00000000296ce078 r15=0x0000000000000000
	eflags=0x0000000000010202
2.1.0-1-(Mar 17 2019 23:59:56) WinVer=61;Rel=;Build=7601;Edition=Professional
-no_dynamic_options -disasm_mask 8 -logdir 'C:\Users\xxx\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'D:\Program Files\Dr. Memory\bin64\release\drmemorylib.dll;0;`-no_check_delete_mismatch` -logdir `C:\Users\xxx\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\xxx\AppData\Roaming\Dr. Memory\symcache`
D:\Program Files\Dr. Memory\bin64\release\drmemorylib.dll=0x0000000002620000
D:\Program Files\Dr. Memory\bin64\release/dbghelp.dll=0x00000000028c0000
C:\Windows/system32/ADVAPI32.dll=0x0000000002b70000
C:\Windows/system32/sechost.dll=0x0000000000b10000
C:\Windows/system32/RPCRT4.dll=0x0000000002c50000
C:\Windows/system32/msvcrt.dll=0x0000000002460000
C:\Windows/system32/kernel32.dll=0x0000000002a50000
C:\Windows/system32/KERNELBASE.dll=0x0000000
```

after run with -debug -dr_debug:
```
ASSERT FAILURE (thread 3792): D:\drmemory_package\drmemory\fastpath_x86.c:1004: mi->memsz <= 4 (load2x of 8-byte memop not supported)
```

**Comment by drumboon** [comment]
Hi Derek,

I came across this issue as well (see below). I saw that you already have scheduled work on fastpath (https://github.com/DynamoRIO/drmemory/issues/262), or is that unrelated? In the meantime, any thoughts on how to test my application with Dr.Memory?

<Starting application viewer.exe (9400)>
<Running on newer-than-this-build "Microsoft Windows 10-1809 x64">
<Early threads found>
<Initial options = -no_dynamic_options -logdir 'Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin64\debug\drmemorylib.dll;0;-visual_studio -logdir `Dr. Memory` -symcache_dir `Dr. Memory\symcache` -lib_blacklist `C:\Windows*.d??,C:\Program Files\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 9400 ' -code_api -probe_api -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0K -reset_every_nth_pending 0 -vm_size 262144K -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
         Dr. Memory version 2.3.0
         Running "viewer.exe -c 'main.in'"
         Using system call file Dr. Memory\symcache\syscalls_x64.txt
<Not tested @D:\drmemory_package\dynamorio\core\win32\ntdll.c:1423>
<curiosity: rex.w on OPSZ_6_irex10_short4!>
<Application changing protections of system memory at least once (0x00007ffafcf38000-0x00007ffafcf3c000)>
         
         Error #1: UNINITIALIZED READ: reading 4 byte(s)
         [...until...]         
         Error #13: UNINITIALIZED READ: reading 4 byte(s)
         system call NtUserCreateWindowEx parameter value #14
             <system call>
         USER32.dll!VerNtUserCreateWindowEx
             ??:0
         USER32.dll!CreateWindowInternal
             ??:0
         USER32.dll!CreateWindowExW
             ??:0
         Qt5Core.dll!QEventDispatcherWin32::processEvents
             ??:0
         Qt5Core.dll!QEventDispatcherWin32::createInternalHwnd
             ??:0
         qwindows.dll!qt_plugin_query_metadata
             ??:0
         Qt5Gui.dll!QGuiApplicationPrivate::createEventDispatcher
             ??:0
         Qt5Core.dll!QCoreApplicationPrivate::init
             ??:0
         Qt5Gui.dll!QGuiApplicationPrivate::init
             ??:0
         Qt5Widgets.dll!QApplicationPrivate::init
             ??:0
         Qt5Widgets.dll!QApplication::QApplication
             ??:0
         main         
             viewer.cpp(21):
         ASSERT FAILURE (thread 20140): D:\drmemory_package\drmemory\fastpath_x86.c:1004: mi->memsz <= 4 (load2x of 8-byte memop not supported)
         WARNING: application exited with abnormal code 0xffffffff

**Comment by tiwariShubhi** [comment]
Hi 
I am facing the same issue, any update on this ?

**Comment by derekbruening** [comment]
Only scas and cmps set load2x so this must be those triggering this.
