### ISSUE TITLE
strace crashes on Windows 7

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/drmemory#2187]
I've build strace based on drMemory framework but it crashes on Win7.
I don't know what is problem. can I run it somehow (maybe with same args) and get more information about crashing reason?

`drrun.exe -c client.dll -- calc.exe`
![image](https://user-images.githubusercontent.com/49196211/55434488-4484a380-5587-11e9-8b77-a110a0f63499.png)

**Comment by derekbruening** [comment]
Generally the first thing would be to switch to debug build which is much easier to debug.  Do you get any assert or other check firing prior to the crash?

If not, you would then attach windbg at the pop-up about the crash and get a callstack.  You would want to load the symbols first, following the instructions at https://github.com/DynamoRIO/drmemory/wiki/Debugging
```
$><c:\src\dynamorio\tools\windbg-scripts\load_syms
```

**Comment by dvfdr43** [comment]
It was my mistake
