### ISSUE TITLE
Skipping system call [Feature]

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/drmemory#2188]
DynamoRIO supports skipping [syscalls](http://dynamorio.org/docs/dr__events_8h.html#aa37d61a7f9dde4663b8dd4c3a44732f4).
It would be useful to have similar feature from drsyscall interface

**Comment by derekbruening** [comment]
Reminding myself of what the drsyscall interface looks like: the user would be using the base DR pre and post syscall events in any case, and calling drsyscall routines from those.  drsyscall is not providing those syscall events on its own.  So it would seem that the user would use DR's interface for skipping and there is no need to provide something at the drsyscall level.
