### ISSUE TITLE
Shadow initialisations reuse static table.

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/drmemory#2199]
Umbra's static table is reused on multiple instances due to an unset flag, i.e., static_shadow_table_unused.

**Comment by johnfxgalea** [comment]
It must also be said that this might be an intended functionality - that multiple initialisations should use the same table. If this is the case, at the very least we need to add a line and document this behaviour.

**Comment by derekbruening** [comment]
The code does look suspect, with that variable never been set, and being renamed in 
3c0c21e0 from static_shadow_table_is_used to static_shadow_table_unused -- strange.  From talking to @zhaoqin offline: the plan was to support multiple mappings and hence dynamic tables are needed but the code never made it to testing for such cases.
