### ISSUE TITLE
Windows 10 version 1903 unable to inject

### ISSUE THREAD

**Issue by rdstevens** [DynamoRIO/drmemory#2201]
drmemory -version
2.1.0 -- build 1

```
c:\windows\system32>drmemory notepad.exe
ERROR: unable to inject

<press enter to dismiss>
```
```
C:\WINDOWS\system32>"c:\Program Files (x86)\Dr. Memory\dynamorio\bin32\drrun.exe" -v -- notepad.exe
INFO: targeting application: "C:\WINDOWS\system32\notepad.exe"
INFO: app cmdline:  "notepad.exe"
INFO: configuration directory is "C:\Users\RobinStevens/dynamorio"
INFO: created child with pid 7412 for C:\WINDOWS\system32\notepad.exe
ERROR: unable to inject: exec of |(null)| failed
```

**Comment by rdstevens** [comment]
I'm really trying to debug a heap corruption in my own code, but I'm getting:

```
~~Dr.M~~ WARNING: unable to locate results file: can't open C:\Users\RobinStevens\AppData\Roaming\Dr. Memory/resfile.19504 (code=2).
Dr. Memory failed to start the target application, perhaps due to
interference from invasive security software.
Try disabling other software or running in a virtual machine.
~~Dr.M~~ WARNING: application exited with abnormal code 0xc0000005
```

If I capture a dump of the process and load it into a debugger, I see:
```
The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
```

and
```
Unhandled exception at 0x7A363042 in CCTV.exe.19504.dmp: 0xC0000005: Access violation reading location 0x00000000.
```

**Comment by derekbruening** [comment]
Is this the 1903 issue with Dr. Memory's underlying engine DynamoRIO https://github.com/DynamoRIO/dynamorio/issues/3633?

**Comment by rdstevens** [comment]
I think it probably is yes. Latest cronbuild pre-dates your fix. I'll attempt to build from source.

**Comment by rdstevens** [comment]
Latest cronbuild of DynamoRIO still shows same behaviour.

```
C:\code\Debug>c:\Users\RobinStevens\Downloads\DynamoRIO-Windows-7.91.18068-0\bin32\drrun.exe -v -- c:\Windows\System32\notepad.exe
INFO: targeting application: "c:\Windows\System32\notepad.exe"
INFO: app cmdline:  "c:\Windows\System32\notepad.exe"
INFO: configuration directory is "C:\Users\RobinStevens/dynamorio"
INFO: created child with pid 20496 for c:\Windows\System32\notepad.exe
ERROR: unable to inject: exec of |(null)| failed
```

**Comment by derekbruening** [comment]
> Latest cronbuild pre-dates your fix

7.91.18068 from 3 days ago should have the fix in it.  So it sounds like something else.  But given that it was the only thing that needed fixing on others' 1903 machines, I wonder if what you are seeing is somehow specific to your configuration.  

I wonder if you could step through the call to dr_inject_process_inject() from drrun.exe?

**Comment by kmar** [comment]
I observe the same behavior as rdstevens, having a machine where Dr.Memory used to work fine before the 1903 upgrade.

I'd like to help, but cmake configuration fails. I wonder what is the proper way to setup and build with VS2017?

**Comment by rdstevens** [comment]
I'm failing to build in VS2017 too - and can't install VS2013 on this machine.

Are debugging symbols available for the cronbuild builds?

**Comment by derekbruening** [comment]
I now have access to a 1903 machine, and DynamoRIO 7.91.18068 works fine there:

```
% DynamoRIO-Windows-7.91.18068-0/bin64/drrun -stderr_mask 15 -- d:/derek/hello64.exe
<Starting application d:\derek\hello64.exe (10552)>
Hello world!
Goodbye world!
<Stopping application d:\derek\hello64.exe (10552)>
```

Running notepad works fine as well:
```
%  DynamoRIO-Windows-7.91.18068-0/bin32/drrun -v -- c:/windows/system32/notepad.exe
INFO: targeting application: "c:\windows\system32\notepad.exe"
INFO: app cmdline:  "c:/windows/system32/notepad.exe"
INFO: configuration directory is "C:\Users\derek/dynamorio"
INFO: created child with pid 9248 for c:\windows\system32\notepad.exe
INFO: waiting forever for app to exit...
```

So I cannot reproduce this failure to inject.

**Comment by kmar** [comment]
I see, I tried drrun of latest dynamorio cron build and it works for me as well.
Unfortunately the latest cron build dr.memory still doesn't work, so I guess we simply have to wait for a new cron build of dr.memory or try to build ourselves?

**Comment by rdstevens** [comment]
This machine is on the Windows Insider program, "Release Preview" setting. WinVer reports 1903 (OS Build 18362.175)

**Comment by derekbruening** [comment]
Mine is `Version 1903 (OS Build 18362.175)`.  Yes, Dr. Memory's subpackage of DynamoRIO needs to be updated.  I will try to get to that soon.

**Comment by rdstevens** [comment]
My system is operated under a company account (rather than a personal or local account). I've just done a clean Windows 10 (1903 18362.175) using a local only account and drrun 18068 is injecting notepad.exe fine.

**Comment by avaneev** [comment]
DynamoRIO 7.91.18068 does not work with the official Dr.Memory release. "Client library incompatible and should be re-compiled". Application runs, but no code analysis takes place.

**Comment by derekbruening** [comment]
https://github.com/DynamoRIO/drmemory/releases/tag/release_2.2.0 has the fix.

**Comment by derekbruening** [comment]
Note that I took this issue to be about the 1903 crash, not about the "unable to inject" which seemed to happen on the insider build.  Please open a new issue covering the "unable to inject" error if it persists.
