### ISSUE TITLE
Not Working In Windows 10, MinGW

### ISSUE THREAD

**Issue by taiprogramer** [DynamoRIO/drmemory#2203]
### Environment
- Microsoft Windows [Version 10.0.18362.175]
- [MinGW](http://www.mingw.org/)
- [DrMemory-Windows-2.1.0-1.msi](https://github.com/DynamoRIO/drmemory/releases/download/release_2.1.0/DrMemory-Windows-2.1.0-1.msi)
### Program
```c
#include <stdio.h>

int main(void){	
	puts("Hello World");
	getchar();
	return 0;
}
```

### Compile
`gcc main.c -o main`

### Issue
When I run drmemory in my cmd

`drmemory -- main` I got an error message below

```
~~Dr.M~~ WARNING: unable to locate results file: can't open C:\Users\HuynhVanTai\AppData\Roaming\Dr. Me
mory/resfile.6932 (code=2).
Dr. Memory failed to start the target application, perhaps due to
interference from invasive security software.
Try disabling other software or running in a virtual machine.
~~Dr.M~~ WARNING: application exited with abnormal code 0xc0000005
```

**Comment by derekbruening** [comment]
Win10 1903 issue: dup of #2201
