### ISSUE TITLE
Exit code from other-bitwidth frontend not propagated

### ISSUE THREAD

**Issue by teta2k** [DynamoRIO/drmemory#2206]
Hi,
I am trying to get Dr. Memory to return non-zero code on errors, but with no success.
The documented option -exit_code_if_errors doesn't seem to work.
Is anybody else experiencing this?

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DrMemory-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs and only reaches a small number of developers.  For a bug filing, there is not enough information here to act on: what platform, what version, what application, please show precise command lines and precise output, etc.

**Comment by teta2k** [comment]
It was just a mistake while calling drmemory from my bat file.
Should have been "start /wait drmemory.exe [...]"
Thanks!

**Comment by derekbruening** [comment]
Thank you for the explanation.

**Comment by teta2k** [comment]
Actually, it only works if called directly from the bin64 directory. If it is called from the default bin directory, it always returns 0 unfortunately.

**Comment by derekbruening** [comment]
As already stated, please provide detailed evidence: what platform, what version, what application, show precise command lines and precise output and show how we can reproduce the problem.  This option works fine in our experience:

```
% bin/drmemory -exit_code_if_errors 4 -batch -- d:/derek/memory_bugs.exe
~~Dr.M~~ Dr. Memory version 2.2.0
~~Dr.M~~ Running "d:/derek/memory_bugs.exe"
~~Dr.M~~ Using system call file D:\derek\drmemory\build_package\DrMemory-Windows-2.2.0-1\drmemory\logs\symcache\syscalls_wow64.txt
~~Dr.M~~
~~Dr.M~~ Error #1: UNINITIALIZED READ: reading 0x0165b3c0-0x0165b3c4 4 byte(s)
~~Dr.M~~ # 0 main               [d:\derek\memory_bugs.cpp:6]
~~Dr.M~~ Note: @0:00:00.375 in thread 3588
~~Dr.M~~ Note: instruction: cmp    (%ecx) $0x0000000a
hi
~~Dr.M~~
~~Dr.M~~ Error #2: UNADDRESSABLE ACCESS beyond heap bounds: writing 0x0165c414-0x0165c418 4 byte(s)
~~Dr.M~~ # 0 main               [d:\derek\memory_bugs.cpp:9]
~~Dr.M~~ Note: @0:00:00.406 in thread 3588
~~Dr.M~~ Note: refers to 0 byte(s) beyond last valid byte in prior malloc
~~Dr.M~~ Note: prev lower malloc:  0x0165c408-0x0165c414
~~Dr.M~~ Note: instruction: mov    $0x0000000c -> (%edx,%ecx)
~~Dr.M~~
~~Dr.M~~ Error #3: INVALID HEAP ARGUMENT: allocated with operator new[], freed with operator delete
~~Dr.M~~ # 0 replace_operator_delete               [d:\drmemory_package\common\alloc_replace.c:2975]
~~Dr.M~~ # 1 main                                  [d:\derek\memory_bugs.cpp:10]
~~Dr.M~~ Note: @0:00:00.438 in thread 3588
~~Dr.M~~ Note: memory was allocated here:
~~Dr.M~~ Note: # 0 replace_operator_new_array               [d:\drmemory_package\common\alloc_replace.c:2929]
~~Dr.M~~ Note: # 1 main                                     [d:\derek\memory_bugs.cpp:8]
~~Dr.M~~
~~Dr.M~~ Error #4: LEAK 4 direct bytes 0x0165b3c0-0x0165b3c4 + 0 indirect bytes
~~Dr.M~~ # 0 replace_operator_new               [d:\drmemory_package\common\alloc_replace.c:2900]
~~Dr.M~~ # 1 main                               [d:\derek\memory_bugs.cpp:5]
~~Dr.M~~
~~Dr.M~~ ERRORS FOUND:
~~Dr.M~~       1 unique,     1 total unaddressable access(es)
~~Dr.M~~       1 unique,     1 total uninitialized access(es)
~~Dr.M~~       1 unique,     1 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       1 unique,     1 total,      4 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~      11 unique,   141 total,  13993 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: D:\derek\drmemory\build_package\DrMemory-Windows-2.2.0-1\drmemory\logs\DrMemory-memory_bugs.exe.4676.000\results.txt
~~Dr.M~~ WARNING: application exited with abnormal code 0x4

% echo $?
4
```

**Comment by teta2k** [comment]
I've uploaded a side-by-side screenshot here:
https://user-images.githubusercontent.com/4326382/60674946-ef0cab00-9e83-11e9-9d13-91ddf76a4f92.png

System is Windows 10 Pro, version 1803, build 10.0.17134.829
Thank you for your time,

**Comment by derekbruening** [comment]
OK so the key is that if you use the frontend which does **not** match the application (in your case, using the 32-bit drmemory.exe to run the 64-bit test.exe), that frontend goes and launches the other frontend but does not pass on the exit code when that other frontend exits.  There is a simple workaround (use the matching frontend) but this is a bug.

**Comment by teta2k** [comment]
That was the problem, indeed. Thanks for the quick support!
