### ISSUE TITLE
instrumenting VsCppUnit based tests

### ISSUE THREAD

**Issue by IngmarVoigt2** [DynamoRIO/drmemory#2207]
drmemory does not seem to instrument / load pdb's for VsCppUnit based tests (https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp) 

I am launching from VisualStudio with the following command line options, however the output does not allow me to trace back to my code:  `-visual_studio -- "E:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" $(TargetPath) /Platform:x64 `

Do you see any possibilities to do that? Would you need an example to test with?

**Comment by Carrotman42** [comment]
I think this would be better off being sent to the user group, as the issue tracker is for tracking and investigating a specific issue and we try not to use it for general questions about using the tools. Please post here: https://groups.google.com/forum/#!forum/dynamorio-users

In your post, can you explain a bit more about what a 'pdb' is? I don't see that string in the link you provided. In the command line flags you provide I also don't see anything related to DynamoRIO, so I'm not quite sure what you're asking. Can you clarify your question in your future post?

DR should be instrumenting all code that is running in some process, but it is possible that the test code is executing in a different process than you expect.

**Comment by derekbruening** [comment]
Note that there is actually a Dr. Memory-specific users list: https://groups.google.com/forum/#!forum/drmemory-users
We can answer on the DR list as well.
