### ISSUE TITLE
DrMemory Internal Crash

### ISSUE THREAD

**Issue by f10hn** [DynamoRIO/drmemory#2234]
Hello, after an hour of running the application (compiled with VS2017) crashes:

<Application C:\n-SL\ws_cor_vs2017\BFS_20191111_2002\bin\buctr.exe (3388).  Dr. Memory internal crash at PC 0x738314a0.  Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'.  Program aborted.
0xc0000005 0x00000000 0x738314a0 0x738314a0 0x00000001 0x00000020
Base: 0x5f550000
Registers: eax=0x00000000 ebx=0x7f7c0000 ecx=0x00000010 edx=0x6ce75aa0
	esi=0x7f7c0000 edi=0x6ce75aa0 esp=0x18efef78 ebp=0x18efef7c
	eflags=0x000
2.2.0-1-(Jul  1 2019 00:42:20) WinVer=104;Rel=1709;Build=16299;Edition=Enterprise
-no_dynamic_options -disasm_mask 8 -logdir 'C:\old\DrMemory\drmemory\logs\dynamorio' -client_lib 'C:\old\DrMemory\bin\release\drmemorylib.dll;0;-suppress `C:\old\DrMemory\suppress\suppress.txt` -logdir `C:\old\DrMemory\drmemory\logs` -symcache_dir `C:\old\DrMemory\drmemory\logs\symcache` -lib_blacklist `C:\WINDOWS*.d??,C
0x18efef7c 0x7383150c
0x18efef94 0x7382f58b
0x18efefd8 0x5f5cc1db
0x007d3790 0x007d37d0
0x18eb5040 0x012c9d6d
0x056c03c0 0x056c040a
0x056c0400 0x78652e72
0x74637562 0x28fbdc64
0x35c30000 0x00000000
C:\old\DrMemory\bin\release\drmemorylib.dll=0x73800000
C:\old\DrMemory\bin\release/dbghelp.dll=0x5f400000
C:\WINDOWS/system32/ADVAPI32.dll=0x05520000
C:\WINDOWS/system32/sechost.dll=0x035c0000
C:\WINDOWS/system32/RPCRT4.dll=0x055a0000
C:\WINDOWS/system32/SspiCli.dll=0x036e0000
C:\WINDOWS/system32/CRYPTBASE.dll=0x03700000
C:\WINDOWS/system32/bcryptPrimitives.dll=0x03720000
C:\WINDOWS/system32/msvcrt.dll=0x03620000
C:\WINDOWS/system32/kernel32.dll>
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff

**Comment by derekbruening** [comment]
Did you delete the bug report template with all of its questions about versions, etc.?

**Comment by f10hn** [comment]
No, the Output above is the end of my log file (additional Information: it is running on a Citrix virtual machine.

**Comment by derekbruening** [comment]
How did you open this issue and only enter the information you did? 
 A new issue goes to this page https://github.com/DynamoRIO/drmemory/issues/new/choose and from there the bug report template asks for a lot more information than you have provided.  I'm asking how you were able to bypass that template, if you didn't use the template but then delete all the questions.

**Comment by f10hn** [comment]
On http://www.drmemory.org/ I click on Issue Tracker and on https://github.com/DynamoRIO/drmemory/issues I click on New Issue - I had to Login, but there where no template asks.

**Comment by f10hn** [comment]
Last night there was no internal crash message, only:
<Out of memory.  Program aborted.>
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff

**Comment by f10hn** [comment]
Out of memory.  Program aborted.
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff

**Comment by derekbruening** [comment]
> On http://www.drmemory.org/ I click on Issue Tracker and on https://github.com/DynamoRIO/drmemory/issues I click on New Issue - I had to Login, but there where no template asks.

This is a bug in Github.  I reproduced it: if you aren't logged in to Github at the time you click New Issue, then after it has you log in, it bypasses https://github.com/DynamoRIO/drmemory/issues/new/choose and goes straight to https://github.com/DynamoRIO/drmemory/issues/new, which is supposed to be impossible with the `blank_issues_enabled: false` setting.  I will report it to Github.

@f10hn -- please fill in the information in the template at https://github.com/DynamoRIO/drmemory/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by derekbruening** [comment]
> @f10hn -- please fill in the information in the template at https://github.com/DynamoRIO/drmemory/issues/new?assignees=&labels=&template=bug_report.md&title=

I.e., please paste the template into this issue (not asking to file a new issue).

**Comment by f10hn** [comment]
Hello Derek, the message "out of memory", I get tonight, is the crucial hint. In Processexplorer I see, that our application realy needs a great amount of memory. With DrMemory it is too much! I will try to reduce the memory consumption.
