### ISSUE TITLE
Unable to build client with drfuzz API

### ISSUE THREAD

**Issue by poul1x** [DynamoRIO/drmemory#2294]
**Describe the bug**

Building sample drfuzz client is failing on ARM32 if c++ code is being compiled. 
When I use `c++` eabihf compiler instead of `c`  compiler, I get an error message:
```
Scanning dependencies of target client
[ 50%] Building CXX object CMakeFiles/client.dir/client.cpp.o
In file included from /home/user/Documents/dynamorio/drmemory/drmf/include/drfuzz.h:494,
                 from /home/user/Documents/app/client.cpp:37:
/home/user/Documents/dynamorio/drmemory/drmf/include/drfuzz_mutator.h:45:8: error: expected unqualified-id before string constant
 extern "C" {
        ^~~
make[2]: *** [CMakeFiles/client.dir/build.make:63: CMakeFiles/client.dir/client.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/client.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**To Reproduce**

<details>
  <summary>CMakeLists.txt</summary>
  
  ```cmake
cmake_minimum_required (VERSION 3.0)
project (client)

if (NOT DEFINED DynamoRIO_DIR)
  message(FATAL_ERROR "Need to specify directory DynamoRIO_DIR containing DynamoRIOConfig.cmake")
endif ()

if (NOT DEFINED DrMemoryFramework_DIR)
  message(FATAL_ERROR "Need to specify directory DrMemoryFramework_DIR containing DRMFTarget32.cmake")
endif ()

find_package(DynamoRIO REQUIRED)
find_package(DrMemoryFramework REQUIRED)

add_library(client SHARED client.cpp)

# configuration for client library
set(CMAKE_C_FLAGS "${CMAKE_FLAGS_CLI}")
set(CMAKE_CXX_FLAGS "${CMAKE_FLAGS_CLI}")

configure_DynamoRIO_client(client)
use_DynamoRIO_extension(client "drmgr")
use_DynamoRIO_extension(client "drfuzz")
  ```
</details>

[toolchain-arm32](https://github.com/DynamoRIO/dynamorio/blob/master/make/toolchain-arm32.cmake)

[client.c](https://github.com/DynamoRIO/drmemory/blob/master/tests/framework/drfuzz_client_repeat.c)

```bash
mkdir build && cd build
cmake ../ -DCMAKE_TOOLCHAIN_FILE=<toolchain-arm32> -DDynamoRIO_DIR=../dynamorio/cmake -DDrMemory_DIR=../dynamorio/drmemory/cmake
make
```

**Expected behavior**

Build is passing

**Versions**

https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-8.0.18390/DynamoRIO-ARM-Linux-EABIHF-8.0.18390.tar.gz

And two earlier relases

**Comment by johnfxgalea** [comment]
Would be great if you can give a reason why you closed this issue - was it a false alarm or did you solve a problem which other users may encounter in the future? Thanks!

**Comment by poul1x** [comment]
I use c++ stuff in another file and use functions with extern "C" modifier to export API. Main file still has `.c` extension. That's the way I've solved my problem
