### ISSUE TITLE
Missing system call information: WinVer=105;Rel=2004;Build=19041;Edition=Professional.

### ISSUE THREAD

**Issue by jannick0** [DynamoRIO/drmemory#2314]
* Dr. Memory version 2.3.18510 build 0 built on Sep 12 2020 00:17:24
* Windows10, Version 2004, Build 19041.508
~~~
~~Dr.M~~ System call information is missing for this operating system: WinVer=105;Rel=2004;Build=19041;Edition=Professional.
~~~
I hope that the information are sufficient, please let me know otherwise.

Thanks.

**Comment by iD4rksid3** [comment]
Same here, windows 10 2004

**Comment by derekbruening** [comment]
That is an expected message.  With the system call info completely changing with each major Windows release, the info is now downloaded the first time Dr. Memory starts up.  Dr. Memory continues after that message, downloads the info, and then runs the target program.

**Comment by jannick0** [comment]
Aaaah, this is new to me.  However, I must have been offline when running `Dr. Memory` the first time.  The error message mentioned above kept popping up. 

But after unzipping `Dr. Memory` again everything happened as you said ... this time I made sure that I was online.  Not sure if it was a good idea to check if the first- run-procedures suceeded or not. 

Thanks again!

**Comment by Mazdaywik** [comment]
What is command line key for suppress the message?

**Comment by derekbruening** [comment]
> What is command line key for suppress the message?

To suppress `WARNING: System call information is missing for this operating system version. Attempting to auto-generate system call information...` which is printed only the first time and once successfully generated is never printed again?  `-quiet` avoids printing most things, but I don't see why avoiding the first-time print is high priority.
