### ISSUE TITLE
DynamoRIO debug check failure: D:\drmemory_package\dynamorio\core\win32\ntdll.c:5229 res >= 0 && len <= MAX_CONTEXT_SIZE

### ISSUE THREAD

**Issue by ntfshard** [DynamoRIO/drmemory#2321]
**Describe the bug**
Analysis fails at the beginning, even with administrator rights

**To Reproduce**
1. download & unpack 2.3.0-1 release
2. in command line: \path\to\bin64\drmemory.exe --notepad.exe
3. Exact output or incorrect behavior:
```
~~Dr.M~~ Dr. Memory version 2.3.0
~~Dr.M~~ Running "notepad"
~~Dr.M~~ Using system call file C:\bin\DrMemory-Windows-2.3.0-1\drmemory\logs\symcache\syscalls_x64.txt
~~Dr.M~~ WARNING: application is missing line number information.
~~Dr.M~~
~~Dr.M~~ Error #1: UNADDRESSABLE ACCESS: executing 0x0000000000000000-0x0000000000000001 1 byte(s)
~~Dr.M~~ # 0 <not in a module> (0x0000000000000000)
~~Dr.M~~ Note: @0:00:01.112 in thread 16688
~~Dr.M~~ WARNING: application exited with abnormal code 0xc0000005
```

Please also answer these questions drawn from  https://github.com/DynamoRIO/drmemory/wiki/Debugging#narrowing-down-the-source-of-the-problem :
 - Does the problem go away when running in light mode (pass `-light` to Dr. Memory)? **NO**
 - Does the problem go away when running with the options `-leaks_only -no_count_leaks -no_track_allocs`? **NO**
 - Does the problem go away when running under plain DynamoRIO?  Do this by running `dynamorio/bin32/drrun -- <application and args>` or `dynamorio/bin64/drrun -- <application and args>` depending on the bitwidth of your applicaiton.  (Ignore warnings about "incomplete installation".) **No drrun in package**
 - What happens with the debug version of Dr. Memory and of its underlying engine DynamoRIO?  Try this by passing `-debug -dr_debug -pause_at_assert`.  Are any messages reported?
![image](https://user-images.githubusercontent.com/4844306/98949944-6b4bdf80-2509-11eb-94b2-d7978f58700d.png)

**Expected behavior**
Running application

**Versions**
 - What version of Dr. Memory are you using?  **2.3.0-1-(Feb  6 2020 06:08:06)**
 - Does the latest build from
https://github.com/DynamoRIO/drmemory/wiki/Latest-Build solve the problem? DrMemory-Windows-2.3.18510: Got 2 different errors, but at least output w/ memory errors appear:
```
~~Dr.M~~ ERROR: Failed to find "main" for limiting memory dump
```
```
~~Dr.M~~ Note: @0:00:06.587 in thread 24000
~~Dr.M~~ Note: next higher malloc: 0x00000225f3e20d60-0x00000225f3e21860
~~Dr.M~~ Note: refers to 0 byte(s) beyond last valid byte in prior malloc
~~Dr.M~~ Note: prev lower malloc:  0x00000225f3e204b0-0x00000225f3e20d3e
~~Dr.M~~ Note: instruction: mov    0xfffffff8(%rax) -> %rdx
<Application C:\WINDOWS\system32\notepad.exe (20208).  Dr. Memory internal crash at PC 0x00000000710cafbb.  Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'.  Program aborted.
0xc0000005 0x00000000 0x00000000710cafbb 0x00000000710cafbb 0x0000000000000001 0x000000007118dcbc
Base: 0x0000000071000000
Registers: eax=0x0000000000000001 ebx=0x0000022573f19c80 ecx=0xffffffffffffffff edx=0x0000000000000001
        esi=0x000000d8b2d7efe8 edi=0x0000000000000000 esp=0x000000d8b2d7eea8 ebp=0x0000000000000000
        r8 =0x0000000000000000 r9 =0x0000000000000000 r10=0x0000000000000000 r11=0x0000000000000246
        r12=0x0000000000000001 r13=0x0000000000000000 r14=0x000000d8b2d7f500 r15=0x0000000000000000
        eflags=0x0000000000010286
2.3.18510-0-(Sep 12 2020 00:17:24) WinVer=105;Rel=2004;Build=19041;Edition=Enterprise
-no_dynamic_options -disasm_mask 8 -logdir 'C:\bin\DrMemory-Windows-2.3.18510\drmemory\logs\dynamorio' -client_lib 'C:\bin\DrMemory-Windows-2.3.18510\bin64\release\drmemorylib.dll;0;-logdir `C:\bin\DrMemory-Windows-2.3.18510\drmemory\logs` -symcache_dir `C:\bin\DrMemory-Windows-2.3.18510\drmemory\logs\symcache` -lib_blac>
```
- What operating system version are you running on? **WinVer=105;Rel=2004;Build=19041;Edition=Enterprise**
- Is your application 32-bit or 64-bit? **64**

**Additional context**
Duplicate of #2208 ? (lines slightly mismatch)

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 7 GenuineIntel ~3504 Mhz

Display name:     Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz

**Comment by ntfshard** [comment]
It looks like this issue should be submitted in DynamoRIO/dynamorio repo actually.

**Comment by derekbruening** [comment]
Yes, dup of #2208 and DynamoRIO/dynamorio#2666.
