### ISSUE TITLE
Leak not always found

### ISSUE THREAD

**Issue by fpom** [DynamoRIO/drmemory#2337]
I run the following program through DrMemory:

```c
#include <stdio.h>
#include <stdlib.h>

int main () {
    char* name;
    printf("What's your name? ");
    scanf("%ms", &name);
    printf("Hello %s!\n", name);
}
```
When started from command line, the leak is found.
When started from a Python program, the leak is not found.
This behaviour is consistent over runs: I always get these results.
The Python code is quite complex, and I was not able to spot what really makes a difference between the two runs:

 - in both cases, DrMemory is run within firejail, in a private directory
 - the environment variables are the same
 - it runs on exactly same Linux system

Furthermore, if I run DrMemory with option `-verbose 32 -debug -dr_debug` it has the same behaviour as before when run through my script (does not find leak), but from the command line, it looks like its stops before to run the program (the expected prompt is not displayed) and I find this into the logs:

```
ASSERT FAILURE (thread 22): /drmemory_package/drmemory/slowpath.c:913: xl8 == pc || IF_X86((options.repstr_to_loop && (opc_is_stringop(opc) || opc == OP_loop) && (xl8 == loc_to_pc(&loc) || xl8 == decode_next_pc(drcontext, loc_to_pc(&loc)))) ||) (instr_at_pc_is_restore(drcontext, ret_pc) && pc == decode_next_pc(drcontext, xl8)) || (options.replace_malloc && opc == IF_X86_ELSE(OP_ret, OP_bx) && alloc_entering_replace_routine(xl8)) (xl8 doesn't match)
```

In order to investigate further, I'd like to know what could cause a difference between two runs of DrMemory, and how I could provide useful information for tracking this issue. I've attached a ZIP file with:

 - directory `src` : the C source file and the bash script that build and run the program
 - directory `direct-DrMemory-a.out.25.000` logfiles when leak is detected
 - directory `python-DrMemory-a.out.25.000` logfiles when leak is not detected
 - directories `debug-*` logfiles when debug options are added

[drmem.zip](https://github.com/DynamoRIO/drmemory/files/5679684/drmem.zip)

Thanks in advance for your help!
Franck

**Comment by derekbruening** [comment]
> When started from a Python program

Via a fork and exec?

If the main() frame was exited, that should be reported as a leak.  `-verbose 4 -debug`, plus knowing what address `name` points at, should give enough info to find where an anchoring pointer was found.  It is possible there's some other value interpreted as a pointer.  Search the log for the address of `name` and it should show the leak scan's examination of it.

The assert is disturbing.  Probably should be a separate issue (unless it's causing a release build issue that is the culprit for the missed leak).

**Comment by fpom** [comment]
> If the main() frame was exited, that should be reported as a leak.

With this sentence you solved my problem!  ;)
Actually, the program was silently killed by the script, and so main() frame was not exited properly.
Thank you ! (And sorry for the noise since it's actually not a bug in DrMemory.)
