### ISSUE TITLE
APP CRASH instr_encode error: no encoding found

### ISSUE THREAD

**Issue by varun729** [DynamoRIO/drmemory#2388]
When I run DynamoRIO with `-t drcachesim` for a python application with Tensorflow, I get a Segmentation Fault (SIGSEGV). 

When running `drrun -debug -loglevel2`, I get the error "DynamoRIO usage error : instr_encode error: no encoding found". Looking in the logs file, I see the following line

**ERROR: Could not find encoding for: lea    0xffffff80(%rcx,%ymm7) -> %rbp**

There are no errors when I run drrun without a client. So the error is specific to `-t drcachesim`.

Build: latest (https://github.com/DynamoRIO/dynamorio/commit/df18aa86c2d5b2c3eb0bb2d487a22b7c9dda0d01)
OS: Linux 5.3.0-53-generic ~18.04.1-Ubuntu
Hardware: AMD Ryzen Threadripper 1950X (AVX2 supported)
Application: python 3.7 with Tensorflow 1.15 (64-bit application), running BERT

**Comment by derekbruening** [comment]
This should go to the dynamorio tracker, not the drmemory tracker.  Looks like VSIB addressing though which is https://github.com/DynamoRIO/dynamorio/issues/2985

**Comment by varun729** [comment]
Apologies.. I was for some reason reading the project as DynamoRIO/dynamorio.

Thanks for pointing me to a relevant issue.
