### ISSUE TITLE
Line numbers not visible in report

### ISSUE THREAD

**Issue by kamrapooja** [DynamoRIO/drmemory#2394]
Please tell me the settings of DrMemory to get the line numbers for memory leak. As of now i am getting report without line number :
[potential_errors.txt](https://github.com/DynamoRIO/drmemory/files/6192151/potential_errors.txt)

please help.

**Comment by derekbruening** [comment]
It looks like you are running `cmd.exe` which does not normally have debug information with line numbers available so this is what would be expected, right?

```
Potential Error #11: HANDLE LEAK: KERNEL handle 0x00000200 and 0 similar handle(s) were opened but not closed:
# 0 system call NtOpenThread
# 1 KERNELBASE.dll!OpenThread    
# 2 cmd.exe!?                             +0x0      (0x0093092e <cmd.exe+0x1092e>)
# 3 cmd.exe!?                             +0x0      (0x0093698a <cmd.exe+0x1698a>)
# 4 KERNEL32.dll!BaseThreadInitThunk
```

**Comment by kamrapooja** [comment]
How i need to run it? Please help.

**Comment by derekbruening** [comment]
Please see the documentation https://dynamorio.org/drmemory_docs/page_running.html for general information on how to run.  For specific questions, please use the users list https://groups.google.com/forum/#!forum/DrMemory-Users, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for bug reports.
