### ISSUE TITLE
Internal Crash on Windows 10

### ISSUE THREAD

**Issue by jay-fenton** [DynamoRIO/drmemory#2405]
**Describe the bug**
Dr. Memory internal crash on Windows 10 running a cpp executable. 

**To Reproduce**
1. I cannot share the specific executable, but can try to create something to reproduce if necessary. 
2. Exact command used:
```
drmemory -batch -ignore_kernel -exit_code_if_errors 1 -suppress win_dr_mem_suppressions.txt TestRunner.exe <additional args>
```
3. Exact output or incorrect behavior.
```
~~Dr.M~~ Using system call file C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt
~~Dr.M~~ C:\Program Files (x86)\Dr. Memory\bin\syscalls_wow64.txt does not contain an entry for this kernel.
~~Dr.M~~ Running on an unsupported operating system version: WinVer=105;Rel=2009;Build=19042;Edition=Enterprise.
TestRunner.exe 3048). Dr. Memory internal crash at PC 0x74d0d111. Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'. Program aborted.
0xc0000005 0x00000000 0x610dd111 0x610dd111 0x00000000 0x00000000
Base: 0x61170000
Registers: eax=0x00000000 ebx=0x00efc1b8 ecx=0x1fd31318 edx=0x00000001
        esi=0x00000000 edi=0x1f411af4 esp=0x00efbe68 ebp=0x00efc128
        eflags=0x000
2.3.0-1-(Feb  6 2020 06:09:03) WinVer=105;Rel=2009;Build=19042;Edition=Enterprise
-no_dynamic_options -disasm_mask 8 -logdir 'C:\Users\jfenton\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\release\drmemorylib.dll;0;`-ignore_kernel` `-exit_code_if_errors` `1` `-light` -suppress `C:\<path>\win_dr_mem_suppressions.txt` -logdir `C:\Users\jfenton
0x00efc128 0x610dfe8a
0x00efc160 0x610ddbf4
0x00efc178 0x610ddf16
0x00efc190 0x610e3348
0x00efc1dc 0x610ebfc0
0x00efc230 0x610b9e17
0x00efc248 0x6104d2f4
0x00efc294 0x6104d74e
0x00efc2f0 0x6104db5f
0x00efd2dc 0x6106a9a7
0x00efd30c 0x6105c21d
0x00efd360 0x61061097
0x00eff320 0x6106114a
0x00eff36c 0x738862d3>
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```

 - Does the problem go away when running in light mode (pass `-light` to Dr. Memory)?
 No.
 - Does the problem go away when running with the options `-leaks_only -no_count_leaks -no_track_allocs`?
 Yes, only with all three options provided.
 - Does the problem go away when running under plain DynamoRIO?  Do this by running `dynamorio/bin32/drrun -- <application and args>` or `dynamorio/bin64/drrun -- <application and args>` depending on the bitwidth of your applicaiton.  (Ignore warnings about "incomplete installation".)
Yes.
 - What happens with the debug version of Dr. Memory and of its underlying engine DynamoRIO?  Try this by passing `-debug -dr_debug -pause_at_assert`.  Are any messages reported?
```
<Starting application C:\<path>\TestRunner.exe (18840)>
<Running on newer-than-this-build "Microsoft Windows 10-2009 x64">
<unknown API-MS-Win pseudo-dll api-ms-win-core-pcw-l1-1-0.dll>
<Initial options = -no_dynamic_options -logdir 'C:\Users\jfenton\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;`-ignore_kernel` `-exit_code_if_errors` `1` `-pause_at_assert` -suppress `C:\<path>\win_dr_mem_suppressions.txt` -logdir `C:\Users\jfenton\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\jfenton\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\WINDOWS*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 18840 ' -code_api -probe_api -msgbox_mask 0 -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0K -reset_every_nth_pending 0 -vm_size 262144K -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr >
<Application TestRunner.exe (18840).  Internal Error: DynamoRIO debug check failure: D:\drmemory_package\dynamorio\core\win32\loader.c:787 !is_dynamo_address(dcontext->app_fls_data)
(Error occurred @0 frags) 
```

**Expected behavior**
Dr. Memory runs without encountering an internal error.

**Screenshots or Pasted Text**

**Versions**
 - What version of Dr. Memory are you using?
2.3.0 -- build 1
 - Does the latest build from
https://github.com/DynamoRIO/drmemory/wiki/Latest-Build solve the problem?
Yes (DrMemory-Windows-2.3.18722.msi).
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
WinVer=105
Rel=2009
Build=19042
Edition=Enterprise
- Is your application 32-bit or 64-bit?
32 bit.

**Additional context**

**Comment by jay-fenton** [comment]
Another team member tracked down some unusual settings and VS configurations on the specific machine that produced these build that crashed. Other machines with consistent settings used to build the application did not have the same behavior. I am closing this out since it appears the build environment was at fault here.

**Comment by derekbruening** [comment]
Thank you for the update.
