### ISSUE TITLE
how to disable open results.txt after exit analysis ??

### ISSUE THREAD

**Issue by jjpark78** [DynamoRIO/drmemory#2454]
Hi. newbie here. 

i want to ask "how to disable open results.txt after done analysis"

due to i am running this program in headless environments (which is gitlab ci/cd runner), 

dr.memory trying to open results.txt (usually execute notepad.exe) is not good for me. 

is there any option for disable open results.txt file or just print errors to stderr only (no any of logs files)

thanks.

**Comment by derekbruening** [comment]
The issue tracker is for reporting bugs, not asking a question.  Please use the users list https://groups.google.com/forum/#!forum/DrMemory-Users for questions.  The bug template says this right at the top: https://github.com/DynamoRIO/drmemory/issues/new?assignees=&labels=&template=bug_report.md&title=
