### ISSUE TITLE
Failed to launch due to missing libunwind.so

### ISSUE THREAD

**Issue by Lowpower** [DynamoRIO/drmemory#2467]
**Describe the bug**
<Application /export/servers/rpc_creative_server/bin/rpc_creative_server (26307). Unable to load client library: libunwind.so.8
	Unable to locate library! Try adding path to LD_LIBRARY_PATH.>
<Application /export/servers/rpc_creative_server/bin/rpc_creative_server (26307). Unable to load client library: libdrmemorylib.so: unable to process imports of client library..>

*version**
2.5.19287

**Comment by derekbruening** [comment]
I would guess that the only issue is that your machine is missing libunwind.  Did you try `sudo apt install libunwind8`?

**Comment by Lowpower** [comment]
but I can install old version(2.3.0-1), that has not this error

**Comment by derekbruening** [comment]
> but I can install old version(2.3.0-1), that has not this error

The old version doesn't use libunwind and the alternatives it uses can produce missing callstack frames with newer distro system libraries.

Sounds like the only action item here is explicitly listing this in the docs.
