### ISSUE TITLE
broken link to drcov documentation

### ISSUE THREAD

**Issue by tonycoz** [DynamoRIO/drmemory#2469]
**Describe the bug**

The page https://drmemory.org/page_coverage.html links to http://dynamorio.org/docs/page_drcov.html which doesn't exist.

Presumably this should link to https://dynamorio.org/page_drcov.html instead.

**To Reproduce**

1. browse to https://drmemory.org/page_coverage.html
2. click on link embedded in the text "For a full description of the drcov2lcov usage see the drcov documemtation at http://dynamorio.org/docs/page_drcov.html."
3. 404 error displayed

**Expected behavior**

Display the documentation for drcov

**Screenshots or Pasted Text**
NA

**Versions**
NA

**Comment by derekbruening** [comment]
Thank you for pointing this out.  Hopefully you can submit a pull request to fix it?
