### ISSUE TITLE
Error: failed to create process (error =193) for c\users\..\.dll

### ISSUE THREAD

**Issue by mahzad** [DynamoRIO/drmemory#2479]
I want to test memory leak of dll source code but this error is occurred.

**Comment by derekbruening** [comment]
You can't launch a new process on Windows with just a library so you would expect it to fail with this error.  Please use the users list https://groups.google.com/forum/#!forum/DrMemory-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
