### ISSUE TITLE
Dr Memory can support  AArch64 ?

### ISSUE THREAD

**Issue by wjwhw** [DynamoRIO/drmemory#2482]
I want to use Dr Memroy memory check for  linux and android?

**Comment by ZWUGA** [comment]
I also have the same problem as yours since I failed to compile Dr.memory source code in AArch64 Raspberry Pi4, and there is no binary tar file to use directly. @derekbruening

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DrMemory-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.

**Comment by derekbruening** [comment]
#2016 covers AArch64.  New developers are needed to contribute time to this project.
