### ISSUE TITLE
Drmemory.exe unable yto load client library:bcrpt.dll: library initializer failed

### ISSUE THREAD

**Issue by chenyongquan2** [DynamoRIO/drmemory#2498]
**Describe the bug**
When I try to use Drmemory.exe to analyse my exe to find problem, it shows the following error:
Unbale to load client library: bcrypt.dll: library initializer failed

![image](https://github.com/DynamoRIO/drmemory/assets/101924391/6c1716ba-f1fd-4611-80d2-9d2619602cfc)

But I can found the bcrypt.dll in n my system file
![image](https://github.com/DynamoRIO/drmemory/assets/101924391/bc6cf923-532e-4661-9e1a-0750ecb65227)

![image](https://github.com/DynamoRIO/drmemory/assets/101924391/d858686b-d0f3-4a9a-bbb4-a01f9eb06628)

And my version info:
![image](https://github.com/DynamoRIO/drmemory/assets/101924391/1d1fae51-ed04-460f-aea1-2906584cbb16)

How could I fix these problem

**Comment by Hzlin7** [comment]
![image](https://github.com/DynamoRIO/drmemory/assets/31055209/6c5d0df8-add3-4b68-850a-9b58411571de)
I got the same problem here，have you solved the problem yet?

**Comment by derekbruening** [comment]
I think this was fixed by DynamoRIO/dynamorio#6571

**Comment by derekbruening** [comment]
Pulled into drmemory by #2495
