### ISSUE TITLE
Dr. STrace internal crash at PC 0x02ccb282

### ISSUE THREAD

**Issue by Vio-et** [DynamoRIO/drmemory#2528]
**Describe the bug**
Dr. STrace internal crash at PC 0x02ccb282.

**To Reproduce**
1. Pointer to a minimized application (ideally the source code for it and instructions on which toolchain it was built with).
2. Precise command line for running the application.
3. Exact output or incorrect behavior.

 - What happens with the debug version of Dr. Memory and of its underlying engine DynamoRIO?  Try this by passing `-debug -dr_debug -pause_at_assert`.  Are any messages reported?

**Screenshots or Pasted Text**
If applicable, add screenshots to help explain your problem.  For text, please cut and paste the text here, delimited by lines consisting of three backtics to render it verbatim, like this:
<pre>
```
<Application D:\APP\WeChat\WeChat.exe (25316).  Dr. STrace internal crash at PC 0x02ccb282.  Please report this at http://drmemory.org/issues.  Program aborted.
0xc06d007f 0x00000000 0x02ccb282 0x02ccb282 0x007bf040 0x00000000
Base: 0x5e720000
Registers: eax=0x007befc0 ebx=0x00000000 ecx=0x00000001 edx=0x00000000
        esi=0x02b80000 edi=0x00000000 esp=0x007befc0 ebp=0x007bf01c
        eflags=0x000
version 10.0.19619, custom build
-no_dynamic_options -logdir 'D:\APP\WeChat' -client_lib 'E:\College\Study\Grade 4\Tools\Dr_memory\bin\release\drstracelib.dll;0;-symcache_path `E:\College\Study\Grade 4\Tools\Dr_memory\logs\symbols\WinTypes.pdb\BB00EF018D604443AE6FFFBC56CB76BD2\WinTypes.pdb` -sysnum_file `E:\College\Study\Grade 4\Tools\Dr_memory\drmemory
0x007bf01c 0x5e5e23de
0x007bf074 0x5e5e3b4c
0x007bf0d0 0x5e57c593
0x007bf0fc 0x5e5c4d37
0x007bf130 0x5e59cf0f
0x007bf148 0x5e59e079
0x007bf3c4 0x5e59e23e
0x007bf3e4 0x7381b9b3
0x5e8555f8 0x73800000
0x73800000 0x00000003>
```
</pre>

**Versions**
 - What version of Dr. Memory are you using?
 - DrMemory-Windows-2.6.0.msi
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
- Windows 10.0.22631
- Is your application 32-bit or 64-bit?
64bit
**Additional context**

**Comment by derekbruening** [comment]
There is nothing actionable here: zero information on how to reproduce and without any of the questions filled in.  Closing as invalid.
