### ISSUE TITLE
Unhandled network adapter ioctls in GetAdaptersInfo in Vista+

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#719]
_From [timurrrr@google.com](https://code.google.com/u/timurrrr@google.com/) on December 14, 2011 04:28:38_

-----------------
#include <winsock2.h>
#include <iphlpapi.h>
#include <stdio.h>
#pragma comment(lib, "IPHLPAPI.lib")

int main() {
  IP_ADAPTER_INFO dummy;
  ULONG size = 0;  // force overflow
  if (GetAdaptersInfo(&dummy, &size) != ERROR_BUFFER_OVERFLOW) {  // LINE 9
    printf("No networks\n");
    return 0;
  }

#if 0  // uncomment for more coverage
  char _buffer = new char[size];
  IP_ADAPTER_INFO *infos = (IP_ADAPTER_INFO_)buffer;
  GetAdaptersInfo(infos, &size);
  delete [] buffer;
#endif

  printf("DONE\n");
}
------------------
On Win7 it gives a whole bunch of uninit reports on line 9

Chromium bug: https://code.google.com/p/chromium/issues/detail?id=107425

_Original issue: http://code.google.com/p/drmemory/issues/detail?id=719_

**Comment by DiskGetor** [comment]
NtDeviceIoControlFile 0x12001b 0x12000f @derekbruening

**Comment by DiskGetor** [comment]
my email:
2762713521@qq.com   i am very haapy to talk aout ioctl code with you ,please email to me.

**Comment by DiskGetor** [comment]
another one is:
0x21009A
